### ISSUE TITLE
Set up CI for IBM Cloud Provider

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#102]
/kind bug

/cc @morvencao

**Comment by morvencao** [comment]
Do we need to update travis script or just enable travis in repo settings?

**Comment by gyliu513** [comment]
Enable Travis for this repo is enough, just like cluster-api-provider-openstack.

**Comment by jichenjc** [comment]
I think we already have some test running before we move to this naming space

and I think for the time being we don't want to run some real test on ibm cloud, do we? 
openstack doesn't have 'real' CI which really do some cluster provisioning test, do aws or vsphere have ?

**Comment by morvencao** [comment]
@jichenjc Yes, we already have test for go linter, build binary & images and unit test before moving here.

For aws and gce provider, they have e2e test script with bazel. We need to replace our travis with bazel.

/Assign @morvencao

**Comment by gyliu513** [comment]
@morvencao please refer to https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api-provider-openstack for what OpenStack is doing.

**Comment by morvencao** [comment]
@gyliu513 thanks, will raise a pr to add ibmcloud provider test jobs here: https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs
