### ISSUE TITLE
Refactor PowerVS specs

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1028]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Prajyot-Parab** [comment]
Proposed Spec Changes -

* [ ]  `ServiceInstanceID string` --> `ServiceInstance IBMPowerVSResourceReference`
* [ ]  `Image *IBMPowerVSResourceReference` --> `Image IBMPowerVSResourceReference`
* [ ]  `SysType string` --> `SystemType string`
* [ ]  `ProcType string` --> `ProcessorType PowerVSProcessorType`
* [ ]  `Processors string` --> `Processors intstr.IntOrString`
* [ ]  `Memory string` --> `MemoryGiB int32`
* [ ]  Restructure `IBMPowerVSResourceReference` fields (explore Type field relevance)

Proposed Status Changes -
* Add `ServiceInstanceID *string` field

**Comment by Prajyot-Parab** [comment]
Phase 1 PR - #1035

**Comment by Prajyot-Parab** [comment]
Post discussion with @Karthik-K-N its been decided not to introduce the Type field in `IBMPowerVSResourceReference`, as a result of the same no additional changes are needed for `Image` field and `IBMPowerVSResourceReference` structure. Also for now we will only enforce the `ServiceInstanceID` and not introduce the name support for the same, as it would increase the complexity of the code.

Rest of the checklist items as part of this issue are already completed, will raise a PR for fixing minor commenting details.

**Comment by mkumatag** [comment]
@Prajyot-Parab anything else pending for this issue?

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab anything else pending for this issue?

Nope, closing.
