### ISSUE TITLE
display correct message for kubectl get machine

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/cluster-api-provider-ibmcloud#103]
/kind feature

**Describe the solution you'd like**
```
$ kubectl --kubeconfig kubeconfig get machine     
NAME                    PROVIDERID   PHASE
ibmcloud-master-5rcv6                
ibmcloud-node-cvww2                  
```
Empty display is not good.
we also need `AGE` as cluster

**Comment by jichenjc** [comment]
if I remember correctly, the phase and providerid is optional and should not be displayed by `get machine`  command, it comes from 
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L41

and for providerid , @xunpan you can refer to 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/274/commits

I think `phase` is a little bit hard to set value..

**Comment by jichenjc** [comment]
@xunpan @gyliu513 do we have a way to identical identify a guest on ibmcloud? 
such as we can use openstack:////<uuid> as openstack identifier, what do we want to ibmcloud?

**Comment by gyliu513** [comment]
not sure about this, @xunpan , can you help check?

**Comment by xunpan** [comment]
I'm not sure if this is an convention or not. I'd like to follow the way you mentioned for `openstack`.
 - `aws` provider uses `aws:////instanceid`
 - `azure` provider uses `azure:////VMID`

 For IBM Cloud, I plan to use `ibmcloud:////guestid`

**Comment by jichenjc** [comment]
ok, let's use ibmcloud for now, thanks for bring this out
