### ISSUE TITLE
CLI tool for Cluster API Provider IBM Cloud

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1052]
/kind feature
/area provider/ibmcloud

Box note [link](https://ibm.ent.box.com/notes/1122570161809?s=wwoa7ui1tdy9gs89pwxekd7xjyfq4hls) to update the contributors to command

* References

1. cli tool [proposal](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/docs/proposal/20230113-capibm-cli-tool.md)
2. cli tool implementation [directory](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/tree/c3579ea7a6bc6020c880b2b564588602e926d687/cmd/capibmadm)
3. [PR](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1027) which added the initial implementation
4. Power VS api reference: https://cloud.ibm.com/apidocs/power-cloud#introduction

* Existing cli for reference:

1. pvsadm: https://github.com/ppc64le-cloud/pvsadm/tree/main/cmd
2. clusterctl: https://github.com/kubernetes-sigs/cluster-api/tree/main/cmd/clusterctl/cmd
3. clusterawsadm: https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/main/cmd/clusterawsadm/cmd

* Recordings related to  cluster api 
1. https://cluster-api.sigs.k8s.io/developer/guide.html#videos-explaining-capi-architecture-and-code-walkthroughs

* List of PowerVS commands to implement

- [x] capibmadm powervs network list - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1075
- [x] capibmadm powervs network create - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1159
- [x] capibmadm powervs network delete - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1159

- [x] capibmadm powervs image list - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1127

- [x] capibmadm powervs port list - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1084
- [x] capibmadm powervs port create - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1090
- [x] capibmadm powervs port delete - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1086

- [x] capibmadm powervs key list - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1083
- [x] capibmadm powervs key create - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1087
- [x] capibmadm powervs key delete - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1087

* List of VPC commands to implement

- [x] capibmadm vpc image list - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1071

- [x] capibmadm vpc key list - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1083
- [x] capibmadm vpc key create - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1113
- [x] capibmadm vpc key delete - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1113

* Command implementation completion task list

- [ ] Update [enhancement](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/docs/proposal/20230113-capibm-cli-tool.md) proposal with any new arguments added to command
- [ ] Update the [capi book](https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/tree/c3579ea7a6bc6020c880b2b564588602e926d687/docs/book/src/topics/capibmadm) with details of new command

* Ship command part of release

**Comment by Prajyot-Parab** [comment]
Note - Interested folks can pick up any command and start working on the same, ensure you comment on the issue the command you will be working on to avoid conflict.

**Comment by Karthik-K-N** [comment]
Lets wait till this [PR](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1027) reviewed and get merged. So will have a good reference to start

**Comment by kishen-v** [comment]
Hi @Karthik-K-N, @Prajyot-Parab,

I'd like to take up the implementation of `capibmadm powervs key list` as an initial effort towards for CLI tool. I've updated the box note with the required information. 

Thank you!

**Comment by dharaneeshvrd** [comment]
Hi All,

I would like to take up the implementation of `capibmadm vpc image list` command.

**Comment by dharaneeshvrd** [comment]
One comment is that it would be great to use context methods wherever available.
So that we can use context.Cancel() to exit from the command execution when needed.

**Comment by KeerthanaAP** [comment]
Hi All,
I would like to take up the implementation of `capibmadm powervs image list` command.

**Comment by dharaneeshvrd** [comment]
Hi All,

Wanted to get opinion on how to display the results for list commands? 
one option is to use ibmcloud cli sdk's terminal package - https://github.com/IBM-Cloud/ibm-cloud-cli-sdk/blob/master/bluemix/terminal/ui.go#L12
another option is to follow the pvsadm's table way - https://github.com/ppc64le-cloud/pvsadm/blob/main/pkg/utils/table.go

IMO we can go with pvsadm way. It seems simple to use and already have an example usage in pvsadm tool.

**Comment by mkumatag** [comment]
> another option is to follow the pvsadm's table way - https://github.com/ppc64le-cloud/pvsadm/blob/main/pkg/utils/table.go
> 
> IMO we can go with pvsadm way. It seems simple to use and already have an example usage in pvsadm tool.

I initially wrote this package but it is got some limitations like does't print the pointers.. may we need to find a new one or fix the limitations with the existing utility..

**Comment by Karthik-K-N** [comment]
> Hi All,
> 
> Wanted to get opinion on how to display the results for list commands? one option is to use ibmcloud cli sdk's terminal package - https://github.com/IBM-Cloud/ibm-cloud-cli-sdk/blob/master/bluemix/terminal/ui.go#L12 another option is to follow the pvsadm's table way - https://github.com/ppc64le-cloud/pvsadm/blob/main/pkg/utils/table.go
> 
> IMO we can go with pvsadm way. It seems simple to use and already have an example usage in pvsadm tool.

Not sure how it prints but here is a reference to cluster api aws: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/cmd/clusterawsadm/printers/printers.go

**Comment by mkumatag** [comment]
> Not sure how it prints but here is a reference to cluster api aws: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/cmd/clusterawsadm/printers/printers.go

This looks good, lets explore this package..

**Comment by dharaneeshvrd** [comment]
It seems here also pointer is not handled by default, we can only define the type as plain data types like its listed here https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#data-types
So might need nil pointer validation from our side.

**Comment by Prajyot-Parab** [comment]
@Karthik-K-N Can you please update the list of commands completed and the ones pending if any.

**Comment by Karthik-K-N** [comment]
Pending commands
1. capibmadm powervs network create
2. capibmadm powervs network delete
3. capibmadm powervs key list

**Comment by mkumatag** [comment]
@Prajyot-Parab lets get the docs sorted out.

**Comment by mkumatag** [comment]
@Karthik-K-N @Prajyot-Parab what else pending in this task for the 0.5 release

**Comment by Prajyot-Parab** [comment]
Docs updated with details of capibmadm tool and related commands

lgtm for release

**Comment by Karthik-K-N** [comment]
Only powervs image import is pending, Apart from that everything lgtm

**Comment by Prajyot-Parab** [comment]
> Only powervs image import is pending, Apart from that everything lgtm

@KeerthanaAP Any update on the import command progress?

**Comment by Prajyot-Parab** [comment]
> Only powervs image import is pending, Apart from that everything lgtm

@Karthik-K-N This got merged, feel free to close this one if no more items are pending.
