### ISSUE TITLE
Update the calico spec in the e2e

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1059]
/kind cleanup
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish can you please help @Amulyam24 to locate the latest location for the calico spec?

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish can you please help @Amulyam24 to locate the latest location for the calico spec?

The latest release is 3.25.1. (We are using 3.24.5 as the default version in k8s-ansible scripts)

https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/calico.yaml
