### ISSUE TITLE
Pushing the doc website for all the different branches

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1096]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Now we have different docs content for the different branches, lets explore how to publish the different docs for all the branches we have in the repository.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Prajyot-Parab** [comment]
Ref - https://github.com/kubernetes/org/issues/4118

**Comment by Prajyot-Parab** [comment]
Pending PR - https://github.com/kubernetes/k8s.io/pull/5397

**Comment by Prajyot-Parab** [comment]
Pending PR - https://github.com/kubernetes/org/issues/4318

**Comment by Prajyot-Parab** [comment]
Update - https://github.com/kubernetes/org/issues/4318#issuecomment-1690306779

Everything working as expected.
