### ISSUE TITLE
Build/Push linux/arm64 arch images as well

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1112]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
We have seen the following error while running on M1 chip Mac, lets push images for the linux/arm64 platform as well.
```shell
$ docker pull k8s.gcr.io/capi-ibmcloud/cluster-api-ibmcloud-controller:v0.4.0
v0.4.0: Pulling from capi-ibmcloud/cluster-api-ibmcloud-controller
no matching manifest for linux/arm64/v8 in the manifest list entries
$
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by swastik959** [comment]
@mkumatag hi I want to work on this issue can you explain it to me
