### ISSUE TITLE
no docker images under k8scloudprovider

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-ibmcloud#112]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Post the same question here, how to push the docker image in k8scloudprovider, currently, we did not have any docker image under k8scloudprovider org.

cc @gyliu513 @xunpan 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gyliu513** [comment]
We will use `quay.io/cluster-api-provider-ibmcloud`.

```
root@gyliu-c11:~# docker pull quay.io/cluster-api-provider-ibmcloud/ibmcloud-cluster-api-controller:v0.1.0
v0.1.0: Pulling from cluster-api-provider-ibmcloud/ibmcloud-cluster-api-controller
898c46f3b1a1: Pull complete
63366dfa0a50: Pull complete
041d4cd74a92: Pull complete
6e1bee0f8701: Pull complete
d93a12e527a9: Pull complete
087420fbbfa3: Pull complete
Digest: sha256:a920d9ccc5ef600a30911073d491cdc8c500ce6c9a24880d3f0c72a0b9e61af1
Status: Downloaded newer image for quay.io/cluster-api-provider-ibmcloud/ibmcloud-cluster-api-controller:v0.1.0
```

**Comment by hchenxa** [comment]
thanks @gyliu513 , may be we also need to update the https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/Makefile#L38 and  https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/config/manager/manager.yaml#L58
