### ISSUE TITLE
Adopt cluster-api 1.4.x

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1148]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Adopt cluster-api 1.4.x

- [x] cluster-api
- [x] k8s
- [x] golang
- [x] update CI image in the prow

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkumatag** [comment]
@Amulyam24 @Prajyot-Parab lets take care of remaining tasks as well.

**Comment by Prajyot-Parab** [comment]
- Update cluster-api to v1.4.1 #1181
- Update kubekins image to 1.26 [#29250](https://github.com/kubernetes/test-infra/pull/29250)

**Comment by mkumatag** [comment]
@Prajyot-Parab what else is pending part of this issue?

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab what else is pending part of this issue?

Nothing from my end looks all good, @Amulyam24 your thoughts?

**Comment by Amulyam24** [comment]
Looks good, this can be closed.
