### ISSUE TITLE
Enhance the doc

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1152]
/kind cleanup
/kind doc
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Amulyam24** [comment]
The [CAPIBM doc](https://cluster-api-ibmcloud.sigs.k8s.io/) needs to be enhanced to ensure easy understanding by users. The data is not well organized into sections or subsections, lacks indentation, and can make proper use of quoted blocks to highlight important notes. A good starting point for improvements would be the [getting started](https://cluster-api-ibmcloud.sigs.k8s.io/getting-started.html) page.
