### ISSUE TITLE
Push latest image to quay.io via CI process

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#116]
/kind bug
/sig ibmcloud

We should always push controller and clusterctl to quay.io via CI process.

## Controller
```
quay.io/cluster-api-provider-ibmcloud/controller
```

## Clusterctl
```
quay.io/cluster-api-provider-ibmcloud/clusterctl
```

@morvencao

**Comment by xunpan** [comment]
@gyliu513 as we already in account `cluster-api-provider-ibmcloud`, shall we use name `controller` and `clusterctl` for simple. Especially for `clusterctl`, I think it is better descriptive in `docker run quay.io/cluster-api-provider-ibmcloud/clusterctl ...`

**Comment by gyliu513** [comment]
@xunpan +1 to use simple name, you can create PR to fix this.

**Comment by jichenjc** [comment]
+1 to the simple naming given the namespace we added

**Comment by gyliu513** [comment]
@xunpan can you help check how federation v2 push the latest image to `quay.io`? We can follow same way for ibmcloud.

/assign @xunpan

**Comment by xunpan** [comment]
federation push image to `quay.io` when CI succeed. It pushes images for `kubernetes-multicluster/federation-v2` with `canary`, `latest` and tag version, e.g. `v0.0.9`.

**Comment by gyliu513** [comment]
@xunpan Yes, shall we follow same logic for ibmcloud images?

**Comment by xunpan** [comment]
@gyliu513  I'm trying to understand how to set credential to access `quay.io` in travis. After that, I will fix this issue.

**Comment by gyliu513** [comment]
>  how to set credential to access quay.io

Yes, this is exactly what we should do.

**Comment by morvencao** [comment]
@xunpan I think we need to put the credential in k8s secret that prow jobs can access.

**Comment by jichenjc** [comment]
only want to make sure my understanding, we will push the image when 
CI passed and merged into master or just CI passed and push to registry for test purpose?
both works for me but I want to make sure I understand the correct way, thank you @morvencao @gyliu513 @xunpan

**Comment by xunpan** [comment]
The logic is pushing image after CI passed for `canary` image. The code at the moment is not merged yet. CI is prerequisite for merge but not do code merge automatically.

For release versioned and latest (latest release one), they are only push by a tag (for release).

**Comment by xunpan** [comment]
@morvencao I guess it is not for this case to pass credential manually by k8s secret. It is better to set it in security place and follow up existing practise.

**Comment by xunpan** [comment]
`federation v2` uses travis ci but ibmcloud cluster api uses `test-infra`.

**Comment by xunpan** [comment]
I think it has no existing ways to push image automatically to cloud and keep security private in test-infra.
    - there is no response from sig-testing community in slack
    - checked related provider and their settings in test-infra
 
I'm still thinking is it necessary to make automatically pushed. 
  - For end users, they can use released image. We upload it in each release by the script. The lates version seems makes less sense to them.
  - For develpers, they can build their own version by the scripts.

Any comments? @gyliu513

**Comment by gyliu513** [comment]
@xunpan +1 for this, let me close this issue.
