### ISSUE TITLE
Build time increased drastically after the buildx added

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1191]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
Have seen build time increased drastically post including buildx, lets explore how to reduce this time.

![image](https://user-images.githubusercontent.com/12646029/233539881-65523c08-0c77-48d2-98e5-61fa78a2d62d.png)

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-cluster-api-provider-ibmcloud-push-images

![image](https://user-images.githubusercontent.com/12646029/233540030-7fd9b3c6-acc1-4631-9c24-9fc2ac0bf314.png)

Time increased from ~20min ====> ~40min

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mkumatag** [comment]
@Prajyot-Parab https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/ this might be helpful, explore `BUILDPLATFORM` and `TARGETPLATFORM` options.

**Comment by mkumatag** [comment]
@Prajyot-Parab its failed building the image,

logs: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-ibmcloud-push-images/1655817106739957760

**Comment by Prajyot-Parab** [comment]
Fixed.

/close
