### ISSUE TITLE
Update the cluster-api deps in the release-0.4 and release-0.3 branches

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1205]
/kind cleanup
/area provider/ibmcloud

**What steps did you take and what happened:**
Update release-0.4 and release-0.3 branches with latest available cluster-api code.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Amulyam24** [comment]
Fixed via #1206 and #1207
/close
