### ISSUE TITLE
the "IBM Cloud" is almost invisible

### ISSUE THREAD

**Issue by RitamSamant** [kubernetes-sigs/cluster-api-provider-ibmcloud#1215]
On the introduction page under "Kubernetes Cluster API Provider IBM Cloud" the words "IBM Cloud" is almost invisible beside the Kubernetes and IBM Cloud logo.
![Screenshot (51)](https://user-images.githubusercontent.com/91908473/236688237-0bc37dea-4db8-4a85-8a15-3f8d42408ce6.png)

**Comment by RitamSamant** [comment]
Looks very good @Manthan1313Github I hope the maintainer sir @mkumatag appoints you in this issue so you can make a PR.

**Comment by mkumatag** [comment]
These pages are autogenerated by [mdbook](https://rust-lang.github.io/mdBook/) utility and the source is [here](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/tree/main/docs/book) for the pages. I don't mind if someone want to exploring fixing this.

**Comment by Manthan1313Github** [comment]
@mkumatag 
Adding style attr for background color in svg file, should do the job for readme page in git and landing page.

https://codepen.io/Manthan1313Github/pen/eYPQQJL
