### ISSUE TITLE
Release v0.0.1

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#123]
Will cut branch for v0.0.1 release.

/assign

FYI @xunpan @jichenjc

**Comment by jichenjc** [comment]
do we have a set of fixes to be included in order to release 0.1? 
I thought cluster-api 0.1 has a lot of features, maybe we want to do 0.0.1 instead?

**Comment by gyliu513** [comment]
@jichenjc Yes, I mean v0.0.1, sorry for the typo ;-) Just want to have a basic release to enable end user can play with it.

**Comment by gyliu513** [comment]
It was released at https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/releases/tag/v0.0.1
