### ISSUE TITLE
worker node was not created with v0.0.1

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#126]
/kind bug
/sig ibmcloud

I was using controller image of `quay.io/cluster-api-provider-ibmcloud/controller:v0.0.1` which is build from https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/tree/v0.0.1.

After the master node was provisioned, the namespaces on master node was not created and the related controllers was also not created on master node, so the master will not able to provision worker node.

```
root@liugya-master-rnpl7:~# kubectl get ns
NAME              STATUS   AGE
default           Active   10m
kube-node-lease   Active   11m
kube-public       Active   11m
kube-system       Active   11m
```

/assign @xunpan 

I think the master branch should have same issue.

**Comment by xunpan** [comment]
I used v0.0.1 to build `controller` and `clusterctl`. Both works:
```
$ kubectl --kubeconfig kubeconfig get node
NAME                    STATUS    ROLES     AGE       VERSION
ibmcloud-master-8pjsn   Ready     master    5m38s     v1.14.0
ibmcloud-node-dx84f     Ready     <none>    49s       v1.14.0
$ git branch
* (HEAD detached at v0.0.1)
```

What is your `machine.yaml` and `provider-components.yaml`? What about `cloud-init-output.log` on both host?

**Comment by xunpan** [comment]
I use the `quay.io` imange. It also works.
```
$ kubectl  --kubeconfig kubeconfig get node
NAME                    STATUS    ROLES     AGE       VERSION
ibmcloud-master-fd5vm   Ready     master    16m       v1.14.0
ibmcloud-node-dxpcf     Ready     <none>    8m58s     v1.14.0
```

Based on slack discussion, please try to use at least 2 cpus for your slave node to have a try.

**Comment by gyliu513** [comment]
Thanks @xunpan , it works in my cluster now with same configuration files, let me check more for this.

**Comment by gyliu513** [comment]
Cannot reproduce this issue now, so close it.
