### ISSUE TITLE
platform 'ibmcloud' handling and labeling inconsistencies

### ISSUE THREAD

**Issue by sean-freeman** [kubernetes-sigs/cluster-api-provider-ibmcloud#1268]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**

> NOTE: This may be confused as a feature request, it is a bug. All resource files are prefixed as follows, it is possible these filenames require amendment if they are supposed to refer to specifically to a type of IaaS. File prefixes:
> - `ibmvpc*.file_ext` refer to IBM Cloud infrastructure services, also known as IBM Cloud VPC Infrastructure environment. This correponds to platform `ibmcloud`.
>    - This includes IBM Cloud Virtual Servers and IBM Cloud Bare Metals
> - `ibmpower*.file_ext` refer to IBM Cloud IBM Power Infrastructure environment. This corresponds to platform `powervs`.
>    - This includes IBM Power Virtual Servers
> - No files are provided for and refer to the IBM Cloud Classic Infrastructure environment.
>    - This includes IBM Cloud Virtual Servers **(Classic)** and IBM Cloud Bare Metal **(Classic)**

When loading any OS Image (QCOW2) onto an IBM Cloud Bare Metal [not IC BM (Classic)] and specifying the Platform ID as `ibmcloud`, the IBM Cloud Bare Metal successfully reads the ID + any cloud-init and will correctly boot the node and append to the K8S cluster.

However at boot of the node, this `cluster-api-provider-ibmcloud` does not correctly distinguish the IaaS type and proceeds to install the IBM Cloud Block Storage for Virtual Servers Container Storage Interface (CSI) Driver ([`ibm-vpc-block-csi-driver`](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver)). This is an incorrect action.

This step should be ignored if IaaS Type == Bare Metal, as this type of Block Storage is only for the VMs and not for BMs. Instead, any NVMe drives should be appended to the LVM Local Storage CSI Driver - although I fully appreciate this may be out of scope for `cluster-api-provider-ibmcloud`.

Once completed, the node should be able to operate KubeVirt without further issue. Currently the `cluster-csi-drivers` will report indefinite errors such as:
- `KubeContainerWaiting`
- `KubeDaemonSetRollbackStuck`
- `KubePodNotReady`
- `ContainersNotReady`
- `ContainersNotInitalized`

---

**What did you expect to happen:**

The Bare Metal node is of platform type `ibmcloud`, it is part of the IBM Cloud infrastructure services. It is not `ibmcloud_classic` and it is not `powervs`.

When platform given is `ibmcloud`, regardless of IaaS Type the `cluster-api-provider-ibmcloud` should handle accordingly for any IaaS Type within this platform.

In addition, I would expect label `powervs` to be correctly prefixed `ibmcloud_power_iaas` in accordance with all other API and CLI references to this separate environment.

---

**Anything else you would like to add:**

If this `cluster-api-provider-ibmcloud` deems each Platform ID as a separate type of IaaS, then further arrangements must be made with those further up the dependency chain as (for example) [FCOS code](https://github.com/coreos/stream-metadata-go/blob/main/release/release.go#L53) considers:
- `ibmcloud` Platform ID for either IBM Cloud Virtual Servers or IBM Cloud Bare Metals
- `ibmcloud_classic` Platform ID for either IBM Cloud Virtual Servers (Classi) or IBM Cloud Bare Metals (Classic). Note: the PR exists but was never implemented, hence FCOS Ignition and Afterburn do not have this compatibility.
- `powervs` Platform ID for IBM Power Virtual Servers; although no specific FCOS/RHCOS OS Image is compiled for this platform, the only compiled option is `ibmcloud`.

**Comment by Prajyot-Parab** [comment]
@sean-freeman 
1. We don't support anything related to IBM Cloud Classic Infra, it is out of the scope of this project.
2. Can you please elaborate more on the usecase/deployment and how you were trying it when you say this - 
> However at boot of the node, this cluster-api-provider-ibmcloud does not correctly distinguish the IaaS type and proceeds to install the IBM Cloud Block Storage for Virtual Servers Container Storage Interface (CSI) Driver ([ibm-vpc-block-csi-driver](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver)). This is an incorrect action.
3. Appreciate your inputs on the renaming to specific IAAS and introducing labels, will explore on this front.

**Comment by sean-freeman** [comment]
@Prajyot-Parab

1. I am aware and agree; repeatedly stated in issue text body **`NOT`** (Classic) resources to ensure full clarity and avoid confusion entirely.
2. As I explain above, the inconsistent labeling and related handling is the root cause - everything else is a symptom of this. I will list these out for clarity:
> - Boot FCOS/RHCOS with Platform ID `ibmcloud` using IBM Cloud Virtual Server, everything works as expected ✅ 
> - Boot FCOS/RHCOS with Platform ID `ibmcloud` using IBM Cloud Bare Metal, failure and corruption because the `cluster-api-provider-ibmcloud` incorectly assumes this platform only contains Virtual Servers and attempts to run tasks that are incompatible. :x:
> - Boot FCOS/RHCOS with Platform ID `ibmcloud` using IBM Cloud Virtual Server **(Classic)**, immediate failure as the environment is wrong and not compatible. ✅ 
> - Boot FCOS/RHCOS with Platform ID `ibmcloud` using IBM Cloud Bare Metal **(Classic)**, immediate failure as the environment is wrong and not compatible. ✅ 
> - Boot FCOS/RHCOS with Platform ID `powervs` _(would expect platform to be listed as `ibmcloud_power_iaas`)_ using IBM Power Virtual Servers via IBM Cloud, everything works as expected. ⚠️
