### ISSUE TITLE
Add clear information about the supported IAAS of IBM Cloud

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes-sigs/cluster-api-provider-ibmcloud#1272]
/kind cleanup
/kind documentation
/area provider/ibmcloud

**Describe the solution you'd like**
- Highlight in book and readme VPC & PowerVS as supported IAAS of IBM Cloud

**Anything else you would like to add:**
NA

**Comment by mkumatag** [comment]
reopen for the older releases
