### ISSUE TITLE
CAPI v1.5.0-beta.0 has been released and is ready for testing

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-ibmcloud#1276]
CAPI `v1.5.0-beta.0` has been released and is ready for testing.
Looking forward to your feedback before CAPI 1.5.0 release, the 25th July 2023!

## For quick reference

- [CAPI v1.5.0-beta.0 release notes](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.5.0-beta.0)
- [Shortcut to CAPI git issues](https://github.com/kubernetes-sigs/cluster-api/issues)

## Following are the planned dates for the upcoming releases

|Release|Expected Date|
|-----|-----|
|v1.5.0-beta.x | Tuesday 5th July 2023|
|release-1.5 branch created (Begin [Code Freeze])|Tuesday 11th July 2023|
|v1.5.0-rc.0 released|Tuesday 11th July 2023|
| release-1.5 jobs created | Tuesday 11th July 2023 |
| v1.5.0-rc.x released | Tuesday 18th July 2023 |
| v1.5.0 released | Tuesday 25th July 2023 |

**Comment by mkumatag** [comment]
/assign @Amulyam24 

please give feedback about the migration we have done recently to v1.5.0-beta.0 especially the migration guide helped easily adopting to the recent version or not

**Comment by Amulyam24** [comment]
The migration to CAPI v1.5.0-beta.0 has been smooth. 

The only minor changes required were w.r.to the controller-runtime version bump about which the necessary information was already provided in the [migration guide](https://main.cluster-api.sigs.k8s.io/developer/providers/migrations/v1.4-to-v1.5.html#notes-about-the-controller-runtime-bump) and it was quite helpful.

**Comment by mkumatag** [comment]
@Amulyam24 https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.5.0-rc.0 rc build is out, lets update to that..

**Comment by Amulyam24** [comment]
Updated cluster-api version to `v1.5.0-rc.0,` closing this task now.
