### ISSUE TITLE
Update README to highlight KIND is the recommended for bootstrap cluster

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#131]
/kind bug
/sig ibmcloud

We need to update README at https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud#prerequisites to clarify `KIND` is preferred for bootstrap cluster as claimed at https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/README.md#prerequisites

@hemanthavs

**Comment by mattlmattlmattl** [comment]
I am attempting to do my first issue.  I have signed the CLA, forked and cloned the github k8s repository etc. but can not see where I would pull this README from.  Do I need to also fork/clone github.com/kubernetes-sigs to then pull from there?

I would be happy to address this if I could figure out where to get the file.
Thanks!

**Comment by gyliu513** [comment]
@mattlmattlmattl Yes, you also need to fork https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud and create PR, please refer to https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/CONTRIBUTING.md for how to contribute!

**Comment by mattlmattlmattl** [comment]
OK, updated the file and created a PR - thanks for your help!

Please let me know if I made any errors/did anything wrong and I will attempt to fix.
Thanks!

**Comment by jichenjc** [comment]
I think we can close this now..
