### ISSUE TITLE
Doc on admin.conf get

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-ibmcloud#143]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

we have following in readme:

Special notes on ssh keys and fetching admin.conf

In order to allow clusterctl to fetch Kubernetes' admin.conf from the master node, you must manually create the key pair in IBM Cloud. By default the generated machine.yaml uses cluster-api-provider-ibmcloud to be the sshKeyName. However, you are free to change that.

I think we are using id_ibmcloud to do the admin.conf get ?? (grep id_ibmcloud in the code tree) GetKubeConfig function has this logic, the sshKeyName is for end user to use? @gyliu513 @xunpan 
**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gyliu513** [comment]
@jichenjc Yes, end user can use `id_ibmcloud` to create the key.

**Comment by jichenjc** [comment]
@gyliu513 the doc said it has to use following:
`you must manually create the key pair in IBM Cloud. By default the generated machine.yaml uses cluster-api-provider-ibmcloud to be the sshKeyName`

this is different to what I remember and read from code.. that's the question

**Comment by gyliu513** [comment]
@jichenjc Yes, you can create a PR to update ;-)

**Comment by jichenjc** [comment]
@gyliu513 @xunpan I want to make sure I understand the code logic before change the doc ...

If I use defined ssh key (ibmc is the private key) then I can log on 

root@jichen1:~# ssh -i /home/cloudusr/ibmc root@108.168.190.92
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)

but with 
root@jichen1:~# ssh -i /root/.ssh/id_ibmcloud root@108.168.190.92
root@108.168.190.92's password:

I can't, this is different to the understanding of similar behavior to openstack...

**Comment by jichenjc** [comment]
so I will make the code change first...

**Comment by gyliu513** [comment]
Because we are hard-coding the `id_ibmcloud` here https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/pkg/cloud/ibmcloud/deployer.go#L78 , this may also need some enhancement to enable end user can set up customized key name.

**Comment by jichenjc** [comment]
ok, now I got it , will see anything I can do to the doc ..
