### ISSUE TITLE
Enable customized ssh key for ibmcloud

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#144]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

This is a follow up task for https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/143#issuecomment-492062183 .

Because we are hard-coding the `id_ibmcloud` https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/pkg/cloud/ibmcloud/deployer.go#L78 , this may also need some enhancement to enable end user can set up customized key name.

FYI @jichenjc @xunpan

**Comment by gyliu513** [comment]
@hemanthavs

**Comment by wanghh2000** [comment]
I saw two ways for do not hard-coding `id_ibmcloud`.
1) Use variable like `IBM_CLOUD_SSH_KEY_NAME`  set by `generate-yaml.sh` in current shell, and get the `IBM_CLOUD_SSH_KEY_NAME` in deployer.go.
2) Setting ssh key name in file  `clouds.yaml` or `cluster.yaml`, then get it in deployer.go.

What do you think? @gyliu513 @xunpan @jichenjc

**Comment by jichenjc** [comment]
use env seems overkill unless we really need to 
clouds.yaml is for under cloud setting and cluster.yaml is for cluster setting
so maybe clouds.yaml fit more here due to cluster.yaml we might need follow cluster-api format?

**Comment by wanghh2000** [comment]
cluster.yaml is not a good place to save. SSH key file was just used by cmd cloudctl in local current shell to logon machine of SL, clouds.yaml was used by controller in bootstrap cluster to interact with SL and that needn't the ssh private file. It looks like shouldn't get it from bootstrapcluster and used in local.
