### ISSUE TITLE
Explore LoadBalancer integration with capibm PowerVS K8s cluster

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes-sigs/cluster-api-provider-ibmcloud#1451]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
This task focuses on including loadbalancer support for capibm powervs k8s cluster. This will also involve exploration of Primary/Secondary LB concepts + DHCP configurations .

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

```[tasklist]
### Tasks
```

**Comment by mkumatag** [comment]
/remove-lifecycle stale

This is already targeted for this release, what else is pending part of this task? @Prajyot-Parab @Karthik-K-N

**Comment by Karthik-K-N** [comment]
This is already completed as a part of https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1608
We can close this
