### ISSUE TITLE
Replace reference of POWERVS_PROVIDER_ID_FORMAT with PROVIDER_ID_FORMAT

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1471]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Power VS provider id format has been deprecated and removed via [PR](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1409), [PR](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1404). 

We are supposed to use `PROVIDER_ID_FORMAT` environmental variable or `--provider-id-fmt` flag. 

Need to update code and document to refer the same.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by kishen-v** [comment]
/assign
Will make the required changes.
