### ISSUE TITLE
smoke test is not working as expected

### ISSUE THREAD

**Issue by Amulyam24** [kubernetes-sigs/cluster-api-provider-ibmcloud#1482]
/kind bug
/area provider/ibmcloud

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-ibmcloud-smoke-test

**Comment by Prajyot-Parab** [comment]
@Amulyam24 Is this issue still relevant? seems like a false alarm to me (can you please share more data/log if its persistent)

**Comment by Amulyam24** [comment]
@Prajyot-Parab, yes this is still a relevant issue. If you check the logs of the current runs, the test stops with creating the controller image but the ideally the test should create a kind cluster and check if the controllers are deployed successfully.

Logs from older runs:
<img width="1332" alt="152289762-e00ec253-a7c3-406a-8fbf-1096a6d05367" src="https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/assets/30797554/213eb472-688a-43b4-a985-db549fb4eb5a">

Will check on what changed and fix it.
