### ISSUE TITLE
Handle VPC LB logic without modification of Spec.ControlPlaneEndpoint.Host field

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes-sigs/cluster-api-provider-ibmcloud#1495]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
This task is to Handle VPC LB logic without modification of Spec.ControlPlaneEndpoint.Host field.
The present logic updates the Spec.ControlPlaneEndpoint.Host field while integrating LB, avoid this behavior by introducing new field.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Prajyot-Parab** [comment]
The present logic is needed as per design of how CAPI consumes it

Ref - https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster#infrastructure-provider

> An infrastructureCluster controller is expected to eventually have its spec.controlPlaneEndpoint set by the user/controller.
> 
> The Cluster controller bubbles up spec.controlPlaneEndpoint and status.ready into status.infrastructureReady from the infrastructureCluster.

Ref - https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster#required-status-fields

> The spec object must have the following fields defined:
> 
> controlPlaneEndpoint - identifies the endpoint used to connect to the target’s cluster apiserver.

@mkumatag @Karthik-K-N ^^^

**Comment by mkumatag** [comment]
Thanks.
