### ISSUE TITLE
Fix index pages content in book

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes-sigs/cluster-api-provider-ibmcloud#1511]
/kind documentation
/area provider/ibmcloud

**Describe the solution you'd like**
Fix index page content in book

- https://cluster-api-ibmcloud.sigs.k8s.io/topics/vpc/
- https://cluster-api-ibmcloud.sigs.k8s.io/developer/
- https://cluster-api-ibmcloud.sigs.k8s.io/reference/reference

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by kishen-v** [comment]
Raised #1508, a single PR with the changes for indexes alongside other documentation changes.
