### ISSUE TITLE
Cluster Creation Successful but calico-node-xx pod is in CrashLoopBackOff Status

### ISSUE THREAD

**Issue by hemanth-avs** [kubernetes-sigs/cluster-api-provider-ibmcloud#153]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**

Create the Cluster and Check the Pod Status

![image](https://user-images.githubusercontent.com/5846263/57960568-13f69000-78cf-11e9-8933-02e935e4bf44.png)

`We can see Pod restarted 60+ times.`

Logs

![image](https://user-images.githubusercontent.com/5846263/57960593-338db880-78cf-11e9-80db-509b55e7d17c.png)

**Environment:**

- Cluster-api version: 
- KIND version: 0.2.1
- Kubernetes version: (use `kubectl version`): v1.13.0
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by gyliu513** [comment]
@hemanthavs this maybe a bug of kubeadm.

@morvencao I recalled you also encounter this issue before, any comments for this? If this is a bug of kubeadm, we can open an issue there.

**Comment by morvencao** [comment]
@gyliu513 Yes, I have encountered that, let me try to reproduce this and find the root cause.

**Comment by jichenjc** [comment]
https://github.com/projectcalico/calico/issues/2040
seems point to kube-dns issue...

**Comment by jichenjc** [comment]
I met this again today...

**Comment by jichenjc** [comment]
@hemanth-avs @xunpan @gyliu513 we need give this high priority...


```
root@jichen1:/home/cloudusr/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# kubectl --kubeconfig=kubeconfig  get nodes
NAME                  STATUS   ROLES    AGE     VERSION
jichen-master-g2x5d   Ready    master   22h     v1.14.0
jichen-node-12345     Ready    <none>   3h42m   v1.14.0
jichen-node-67890     Ready    <none>   44m     v1.14.0
jichen-node-s9s2b     Ready    <none>   22h     v1.14.0
name1                 Ready    <none>   5h48m   v1.14.0
```

I have 1+4 cluster above and 

```
root@jichen1:/home/cloudusr/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# kubectl --kubeconfig=kubeconfig  get pods -n kube-system
NAME                                          READY   STATUS             RESTARTS   AGE
calico-node-7zhdp                             0/1     CrashLoopBackOff   63         3h42m
calico-node-9qmtb                             1/1     Running            0          22h
calico-node-ggspb                             0/1     CrashLoopBackOff   97         5h48m
calico-node-w96kf                             0/1     Running            368        22h
calico-node-whb9c                             0/1     CrashLoopBackOff   15         45m
```

apparently all nodes has issue in their calico settings

I am not very expert in network area especailly the calico side, looks like the new node has issue in connecting to svc 10.96.0.1 which is by default the kube-api 
logon to one node and found it has a route here:

```
root@jichen-node-67890:~# ip route
10.0.0.0/8 via 10.109.100.193 dev eth0 proto static
````

so all 10.x.x.x ip will take 10.109.100.193 as gateway and I don't know whether it has some issue

will need further check on following potential point:
1) whether 10.x.x.x reserved by IBM cloud as private IP and lead to ip route to someplace else
2) whether security group blocked the internal IP (less likely because we can kubeadm join ...)

**Comment by gyliu513** [comment]
What is the log of those `CrashLoopBackOff` pods? Is this a bug of `kubeadm`? Does OpenStack works fine?

**Comment by jichenjc** [comment]
log pasted above, I don't think it's kubeadm bug because openstack seems works fine based on my previous test result...  @morvencao have you recently use openstack to create cluster and have this issue?

**Comment by jichenjc** [comment]
run this on the node 
```
iptables -t nat -A PREROUTING -d 10.96.0.1 -j DNAT --to-destination 10.109.100.204
```

calico-node-9qmtb                             1/1     Running            2          3d18h
....
calico-node-whb9c                             1/1     Running            1112       2d20h

fixed the problem (whb9c ) pod, so maybe kube-proxy has some problem ?? need further check on the configuration...

**Comment by morvencao** [comment]
@jichenjc Sorry for the late response, I didn't have time to try this on provider openstack. 

If you check the logs of the failed pod, you can see that the pod can't connect to the api-server:
```
root@mc-dev:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# kc -n kube-system logs -f calico-node-smfx8
Threshold time for bird readiness check:  30s
2019-05-27 11:14:48.306 [INFO][10] startup.go 256: Early log level set to info
2019-05-27 11:14:48.306 [INFO][10] startup.go 272: Using NODENAME environment for node name
2019-05-27 11:14:48.306 [INFO][10] startup.go 284: Determined node name: ibmcloud-node-jkb9p
2019-05-27 11:14:48.307 [INFO][10] startup.go 316: Checking datastore connection
2019-05-27 11:15:18.308 [INFO][10] startup.go 331: Hit error connecting to datastore - retry error=Get https://10.96.0.1:443/api/v1/nodes/foo: dial tcp 10.96.0.1:443: i/o timeout
2019-05-27 11:15:49.309 [INFO][10] startup.go 331: Hit error connecting to datastore - retry error=Get https://10.96.0.1:443/api/v1/nodes/foo: dial tcp 10.96.0.1:443: i/o timeout
```

**Comment by morvencao** [comment]
The reason calico node crashes should be caused by the overlap of the service CIDR and host CIDR;  The default service CIDR is `10.96.0.0/12` while the host IP is 10.xx.xxx.xxx.
So I suggest making sure they do not overlap by changing our default service CIDR from `10.96.0.0/12` to `20.96.0.0/12` in PR: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/191

**Comment by jichenjc** [comment]
ok, let me try this solution first, then I will post some comments based on the PR you submitted and info here, the IBM cloud 10.x.x.x/8 might be the key issue that you suggested @morvencao

**Comment by morvencao** [comment]
@jichenjc Thanks, let's keep default service CIDR unchanged and try to make vm IP configurable.

**Comment by jichenjc** [comment]
I tried to use 20.96.x.x/12 and 172.31.0.0/16 as 
```
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["172.31.0.0/16"]
```

both works for me, so I suggest we use 172.31.0.0/16 as this is enough for us to proceed and still a private IP address, we should document this limitation because of IBM cloud private ip issue and proceed...

@gyliu513 @gyliu513 @xunpan thoughts?

**Comment by gyliu513** [comment]
@jichenjc can we enhance the `clouds.yaml` as follows to enable end user can configure the cidr for the vms?

```yaml
clouds:
  ibmcloud:
    auth:
      apiUserName: "Your API Username"
      authenticationKey: "Your API Authentication Key"
    machines:
      cidrBlocks: ["20.96.0.0/12"]
```

**Comment by morvencao** [comment]
@gyliu513 If have want to use customized CIDR for VM IP other that default `10.x.x.x/8`, then we need to create `subnetwork` and then create VM in that `sebnetwork`, something like openstack,

**Comment by jichenjc** [comment]
@morvencao you mean create a subnet in IBM cloud and then our instance will start to use that network? I didn't try this before but I think it's something we can suggest

so to summarize ,we have to keep '10.96.0.0/12' as the cluster ip and change IBM cloud side?

**Comment by morvencao** [comment]
@jichenjc I thought `subnetwork` or configurable VM CIDR should be support finally. 

For now, I'm not sure if softlayer supports to create customized subnetwork, I didn't find the creation subnetwork interface neither in API, nor in UI portal:https://control.softlayer.com/network/subnets

**Comment by jichenjc** [comment]
I have no idea how IBM cloud runs their IP settings 

looks like we used this subnet (maybe because we used washington 1 zone) and I have no idea why it has a route 10.x.x.x/8 by default and how it connected each other, as far as I can tell seems current IBM cloud doesn't support VPC (see AWS VPC concept) ... so again, for short team, seems modify cluster service IP (it's virtual and nonaccessable to outside) is a good way then we have time for questioning and testing on IBM cloud 10.x IP usage

10.109.100.192/26 | Private | Primary | wdc01.bcr05a.1165 | Washington 1
-- | -- | -- | -- | --

**Comment by morvencao** [comment]
@jichenjc Agreed. Complete fix need to changes in API, at least support configurable CIDR in `Clouds.yaml` or `machines.yaml`, I think. Changing the service CIDR should be a short-term fix.

Comments? @gyliu513
