### ISSUE TITLE
Check if we can learn from vsphere provider for image CI

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#154]
/kind bug
/sig ibmcloud

Please refer to https://github.com/kubernetes/cloud-provider-vsphere/tree/master/hack/images/ci to see if this helps?

/assign @xunpan

**Comment by xunpan** [comment]
It shows a way to push image on go `gcr.io`. It uses secret `cloud-provider-vsphere-e2e-config` to store the credential for login before push. Again, not know how they create and keep credential private.

**Comment by jichenjc** [comment]
can we post some question in their slack channel or submit a issue to ask for additional info? I think it's important for us to have e2e test in long term

**Comment by gyliu513** [comment]
You can also open an issue in vsphere cloud provider repo to ask

**Comment by jichenjc** [comment]
I opened https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/268
but not sure I am asking right thing, @gyliu513 @xunpan please add more info if I have some misunderstanding

**Comment by jichenjc** [comment]
@xunpan can you talk to sig-testing as kubernetes-sigs/cluster-api-provider-vsphere#268 has some comments and I am not very familiar with this .. thanks

**Comment by gyliu513** [comment]
Working at https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/203#issuecomment-496895135
