### ISSUE TITLE
Docs: identifying scope of improvement

### ISSUE THREAD

**Issue by Amulyam24** [kubernetes-sigs/cluster-api-provider-ibmcloud#1545]
/kind documentation
/area provider/ibmcloud

This issue is to collaborate and identify the gaps in the current documentation.
https://cluster-api-ibmcloud.sigs.k8s.io/

**Comment by Prajyot-Parab** [comment]
@Amulyam24 #1402 can we combine both into a single issue. (seems similar)

**Comment by Amulyam24** [comment]
Hi @kishen-v @Niharika0306 @KeerthanaAP @srivastav-abhishek

We are planning to enhance the documentation and make it more understandable and consumable by end users/new comers to the project.

Since you all have recently contributed to or explored this project, I look forward to hearing any feedback on the current documentation. Please share your thoughts accordingly.

**Comment by Amulyam24** [comment]
cc @Shilpa-Gokul @dharaneeshvrd

**Comment by Amulyam24** [comment]
Handled via https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1786
