### ISSUE TITLE
support dedicate host provisioning

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-ibmcloud#155]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

support dedicate host (baremetal), softlayer support baremetal deployment, we only support virtual now.. let's see whether it has value to support not only virtual machine, but also the dedicated host

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
This make sense, as Red Hat already proposed a bare metal provider at https://github.com/metal3-io/cluster-api-provider-baremetal

**Comment by jichenjc** [comment]
yes, that provider is doing by openstack community, I heard they are going to use openstack ironic (standalone version)
