### ISSUE TITLE
Enable Cluster add-on for ibmcloud

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#158]
/kind feature
/sig ibmcloud

@jichenjc can you help check if we can enable cluster add-on for ibmcloud?

FYI @hemanth-avs @xunpan @clyang82 @morvencao

**Comment by jichenjc** [comment]
are you talking about  https://kubernetes.io/docs/concepts/cluster-administration/addons/? or something like https://docs.google.com/document/d/1tpayzZ4teTKOXNUEsA2HK73eWzz9MhZOFTKYz_rRI_8/edit?ts=5cdabdf8#heading=h.f4yb38lpt4z5 ?

**Comment by gyliu513** [comment]
@jichenjc I mean here https://github.com/kubernetes-sigs/cluster-api/tree/master/cmd/clusterctl#creating-a-cluster

![image](https://user-images.githubusercontent.com/4461983/58147196-f12bf900-7c8b-11e9-93c8-4353f5c22957.png)

**Comment by jichenjc** [comment]
ok, seems related to the google doc I attached... will take a look~

**Comment by jichenjc** [comment]
it's not a big deal after some look, it provided a entry to add some addon for the bootup cluster and can be applied here: 

https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go#L213

unless we want to add special stuffs for the new created cluster (maybe we do want but not now?)
we can make it as it is...

of course, we can add this into document and provide additional info... thoughts?

**Comment by gyliu513** [comment]
@jichenjc can we update document by adding an example? Such as installing kubernetes dashboard with `add-ons.yaml`?

**Comment by jichenjc** [comment]
@gyliu513 ok, that's a very good suggestion, I need try and see what's happened there
