### ISSUE TITLE
Handle create workflow of newly proposed Power VS cluster creation method

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1599]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

New way of creating Power VS cluster has been added here https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1488

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Karthik-K-N** [comment]
Most of the code changes are done and it can been seen here https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/tree/update-ignition

**Comment by Amulyam24** [comment]
Added via #1608 
/close
