### ISSUE TITLE
Enhance packer plugin for the powervs dhcp network

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1607]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**

**Anything else you would like to add:**

**Comment by Amulyam24** [comment]
@Karthik-K-N , has this been taken care of with your recent changes to` image-builder` or anything is pending?

**Comment by Karthik-K-N** [comment]
Yea it's taken care of, we can close this as completed
