### ISSUE TITLE
git describe from the Make files state `fatal: No names found, cannot describe anything.`

### ISSUE THREAD

**Issue by kishen-v** [kubernetes-sigs/cluster-api-provider-ibmcloud#1609]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**

A few targets that use `git describe` seem to complain of `fatal: No names found, cannot describe anything.`. 

**What did you expect to happen:**
No warnings or errors.

**Anything else you would like to add:**

This can be fixed with --always along with git describe, which will default to the latest commit hash. However, this seems to break a few of the commands which tend to accept ldflags, such as make docker-build. Thus, the necessary changes are needed to ensure the existing functionality offered.

**Comment by mkumatag** [comment]
@kishen-v any updates?

**Comment by kishen-v** [comment]
Hi @mkumatag, I see that when the repository is forked and `git describe` is executed, the error is observed. Tags are not available in forked repositories. 

I shall work on having this fixed.

**Comment by kishen-v** [comment]
Fix identified: 
This change pulls in the tags from the upstream repository for use in the fork, which will suppress the error message 
```
git remote add upstream https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud.git
git fetch --tags upstream
```
