### ISSUE TITLE
Enable installing multiple controller planes cluster 

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#161]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

IBM Cloud Provider do not support installing a HA cluster (multiple controller planes cluster ) now, we should support this to enable enterprise k8s deployment.

@xunpan can you help check this?

Some discussion for OpenStack provider at https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/346

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
@xunpan https://github.com/kubernetes-sigs/cluster-api/pull/878

**Comment by jichenjc** [comment]
@gyliu513 I think you mentioned ICP might consume this ibmcloud provider repos soon, so the question is the PR you metioned is on master, but providers depends on origin/release-0.1 branch?

**Comment by gyliu513** [comment]
@jichenjc I think Cluster-API will have another release soon, they have released another 0.1.1 version at https://github.com/kubernetes-sigs/cluster-api/releases/tag/0.1.1

**Comment by jichenjc** [comment]
@gyliu513 current provider use release-0.1 branch, will create tag on master branch (without backport) helps us?

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/889..

**Comment by jichenjc** [comment]
I will submit a PR according to https://github.com/kubernetes-sigs/cluster-api/pull/878 (the answer from ncdc), looks like we need some changes in the provider side later...
