### ISSUE TITLE
Investigate how to enable MachineDeployment for IBM Cloud

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#162]
/kind feature
/sig ibmcloud

This can enable end user adding multiple worker node with ease. An example here https://github.com/kubernetes-sigs/cluster-api/blob/master/sample/machinedeployment.yaml

@hemanth-avs can you help work for this?

**Comment by jichenjc** [comment]
this should be transparent to provider ? I understand machinedeployment is for multiple machines reconcile and the logic mostly in cluster-api? anyway, do some analysis might have conclusion paste here
