### ISSUE TITLE
PR jobs are failing on main branch

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1620]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
failing with golang toolchain issue, pal

e.g: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1619

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mkumatag** [comment]
cc @Amulyam24

**Comment by Amulyam24** [comment]
The latest kubekins image being used for the presubmit job is `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240211-f101bf4199-1.27`

The go version tagged to the above image is
```
/workspace# go version
go version go1.21.7 linux/amd64
```
(created a sample pod and checked)

We might need to bump the version as well to avoid the failing issue.

**Comment by mkumatag** [comment]
Lets check the golang version shipped part of 1.27 k8s version and stick to that..

**Comment by mkumatag** [comment]
We are using 1.28 version of k8s and which is already 1.21 golang version, lets bump the files and the kubekins image as well.

**Comment by Amulyam24** [comment]
Updated main branch to go 1.21.
/close
