### ISSUE TITLE
Support alternative methods for IBM Cloud credential injection

### ISSUE THREAD

**Issue by cjschaef** [kubernetes-sigs/cluster-api-provider-ibmcloud#1628]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Currently, the only method to inject the IBM Cloud credentials used by CAPI, is using an environment variable. For example, [vpc command](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/0f5bb7ed7dccd00182fa8143a11855cafc6db568/cmd/capibmadm/cmd/vpc/vpc.go#L37-L40) has a hard requirement for the key environment variable. Alternatively, it would be helpful to offer a method to set or default getting the credentials from a file location instead, relying on the controller to retrieve the credentials from said file instead, rather than possibly exposing the raw credential.

**Anything else you would like to add:**
N/A

**Comment by mkumatag** [comment]
Thanks for creating this issue, [capibmadm](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/tree/main/cmd/capibmadm) is a utility code we are using for creating/listing some of the prerequisites resources needed for the capi cluster creation. Likewise we also have similar approach in the controller code which needs to be addressed first I feel.

**Comment by cjschaef** [comment]
My fault, I hadn't dug deep enough into things to realize some of the options available already.
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/0f5bb7ed7dccd00182fa8143a11855cafc6db568/config/default/credentials.yaml#L8

I'll close this issue with the expectation that the support is available and I'll followup on doing some more learning. Thanks!
