### ISSUE TITLE
After machine resource pivot to target cluster. PHASE does not updated.

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/cluster-api-provider-ibmcloud#165]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
After machine resource pivot to target cluster. PHASE does not updated.
```
$ kubectl --kubeconfig kubeconfig   get machine
NAME                          PROVIDERID              PHASE
a-xun-ibmcloud-master-9ctpf   ibmcloud:////80884143   
```

**What did you expect to happen:**
update PHASE to correct information

**Comment by jichenjc** [comment]
is this a bug of cluster-api? as we seems can't do something in provider side? @xunpan

**Comment by xunpan** [comment]
`Machine` is managed by provider controller. So, `PHASE` is managed by us.
