### ISSUE TITLE
webhook checking

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/cluster-api-provider-ibmcloud#166]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
Machine specific information is not checked which may failed VM instance provision with wrong information.

Let's check available values

**Comment by jichenjc** [comment]
@xunpan do we have a chance to reuse some ibmcloud provider specified code ? I think we should not  invent a webhook wheel as those kind of webhook should already be defined/supported?

**Comment by xunpan** [comment]
It should be good news to me if we've already have a webhook code for reusing. But, I checked `softlayer` go library code, and did not find a webhook for the purpose. 

Could you share where is the code for sharing ?

**Comment by jichenjc** [comment]
I am asking because I knew openstack cloud provider has some logic so I want to double check whether softlayer has so we can avoid make a wheel.. I don't know whether we have or not but we'd better check with folks from ibmcloud first
