### ISSUE TITLE
Add webhook for validating powervscluster.spec.loadbalancer.additionallister.port against 6443

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1663]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

As of today by default we [create](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/cf6572ad5690871e17515db7f94bf22d3551b847/cloud/scope/powervs_cluster.go#L1321-L1339) loadbalancer pool and listner with port 6443.

If knowingly user tries to configure a loadbalancer with same port again it throws error
```
{
  "lastTransitionTime": "2024-03-11T13:54:30Z",
  "message": "Port '6443' is used by another listener instance. Please choose a different port.",
  "reason": "LoadBalancerReconciliationFailed",
  "severity": "Error",
  "status": "False",
  "type": "LoadBalancerReady"
}
```

So better to fail it early with the help of webhook

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by hamzy** [comment]
Is there validation for duplicates in the list?  For numbers outside of an allowed range?
