### ISSUE TITLE
Support pausing the cluster

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1730]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

cluster api supports pausing the workload cluster https://github.com/Karthik-K-N/cluster-api/blob/main/api/v1beta1/cluster_types.go#L48, Explore and add support for it for IBMPowerVSCluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkumatag** [comment]
@Karthik-K-N what else is pending part of this task?

**Comment by Karthik-K-N** [comment]
Everything is done we can close, This.
work is completed via PR https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1769
/close
