### ISSUE TITLE
Support local routing in transit gateway when PowerVS and VPC are from same region

### ISSUE THREAD

**Issue by dharaneeshvrd** [kubernetes-sigs/cluster-api-provider-ibmcloud#1763]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently global routing is enabled by default, would like to enable local routing when PowerVS and VPC are from same region. This will reduce some $$$ 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkumatag** [comment]
what's the different amount for these settings?

> Currently global routing is enabled by default, would like to enable local routing when PowerVS and VPC are from same region. This will reduce some $$$

**Comment by mkumatag** [comment]
do we need to add an additional flag to this spec here like routing - global/local https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/e35abc566042b99a881b4862fedd8566c5f569ea/api/v1beta2/ibmpowervscluster_types.go#L253

**Comment by dharaneeshvrd** [comment]
Still need to investigate that, will run two transit gateways with local and global routing for a couple of days and come back with the cost here!

**Comment by dharaneeshvrd** [comment]
Just created this issue as a placeholder, in case if we are fixing it in hypershift, we can fix here too.

**Comment by dharaneeshvrd** [comment]
Thanks @prb112 for the link!
Below is the cost for data transfer on local and global routing.
$0.01045 per Local egress data (in GB)
$0.0209 per Global egress data (in GB)

Seems global routing costs double than the local routing. So it's better to use local routing in possible situations.

Other thing I found is that reusing transit gateway also could save some dollars, for a new connection its costing around $60 on both local and global routing case. So if we can reuse the existing transit gateways that would save as well. This would make significant difference during development phases.

**Comment by Karthik-K-N** [comment]
I think if user provided PowerVS zone and vpc.Region are within same region we can by default go for local routing and introduce a new field in api to allow user to configure it to use global.

**Comment by mkumatag** [comment]
This needs:
- Additional param in the `TransitGateway` struct
- Validation web book change to make sure user don't use the irrelevant values(e.g: different region requires the global routing)
- Defaulting to use local as routing if powervs and vpc belongs to same region

@Karthik-K-N @dharaneeshvrd feel free to add If I'm missing something

**Comment by dharaneeshvrd** [comment]
Do we really need a param to set the route? Not sure in which case user needs it, can't we just decide local or global based on the powervs and vpc region? What's the point in setting global routing even in cases where it only needs local routing?
@mkumatag @Karthik-K-N Please let me know is this making sense!

**Comment by mkumatag** [comment]
> Do we really need a param to set the route? Not sure in which case user needs it, can't we just decide local or global based on the powervs and vpc region? What's the point in setting global routing even in cases where it only needs local routing? @mkumatag @Karthik-K-N Please let me know is this making sense!

Its always good to give option for user to override, they can set it explicitly for any specific scenario.
