### ISSUE TITLE
Reason to keep VPC and ResourceGroup param in VPC Security Group

### ISSUE THREAD

**Issue by dharaneeshvrd** [kubernetes-sigs/cluster-api-provider-ibmcloud#1770]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
This issue is to continue the discussion on the question asked [here](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1752#issuecomment-2090543765)

> @cjschaef I just have a comment on [VPC](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/732b7732e3aa883d96e88eb03fd932d54030bace/api/v1beta2/types.go#L296) and [ResourceGroup](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/732b7732e3aa883d96e88eb03fd932d54030bace/api/v1beta2/types.go#L284) properties of type SecurityGroup. are you planning to pass a different VPC and Resource Group than the one cluster is using? Just wanted to understand what is the intention for the properties?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by dharaneeshvrd** [comment]
@cjschaef Please revert back when you get a chance!

**Comment by dharaneeshvrd** [comment]
Raised this PR #1783 to remove the VPC and SecurityGroup field for now to make it simple and if need we can add it back.

**Comment by cjschaef** [comment]
The specifications for having a ResourceGroup and VPC defined in the SecurityGroup resource allowed for BYON support to be easier and cleaner.

I will have to re-review and refactor all related VPC functional work to account for the renamed resources and attempt to refactor functionality of SecurityGroup and SGRule creation while keeping the ability of BYON support in mind.

I cannot re-open this issue, so I will open an issue as needed if I indeed have to revert the changes that have been made
