### ISSUE TITLE
reboot master lead to kube service not started 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-ibmcloud#181]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
first reboot the master that deployed, then wait for machine back to start state and see following ....

```
root@jichen-master-g2x5d:~# uptime
 09:12:57 up 14 min,  1 user,  load average: 0.03, 0.03, 0.00
root@jichen-master-g2x5d:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@jichen-master-g2x5d:~# ps aux | grep kube
root      7375  0.0  0.0  14856  1032 pts/0    S+   09:13   0:00 grep --color=auto kube
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
@xunpan do you know whether we need some steps to persistent the configuration such as restart docker container at startup stage?

**Comment by xunpan** [comment]
`kubeadm` should support it. 
https://github.com/kubernetes/kubeadm/issues/110

**Comment by jichenjc** [comment]
let's use https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/293/files
