### ISSUE TITLE
Build Power VS DHCP enabled image with k8s version 1.29.3

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1833]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We need to build the Power VS image compatible with DHCP service.

The instruction to build the image can be found here https://main.cluster-api-ibmcloud.sigs.k8s.io/developer/build-images#powervs

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Some notes from previous experience of building the image
1. The image builder is currently run from x86 machine of VPC which should be connected to to Power VS workspace via TransitGateway because as a part of image building the image builder tries to ssh into VM with DHCP IP of VM which is private.
2. Customisation to Centos OS image should be done to enable DHCP network.

Previously built image details
```
COS_BUCKET_REGION="us-south" 
COS_BUCKET_NAME="power-oss-bucket" 
COS_OBJECT_NAME=capibm-powervs-centos-streams8-1-28-4-1707287079.ova.gz 
```

**Comment by Amulyam24** [comment]
Image created, details
```
COS_BUCKET_REGION="us-south" 
COS_BUCKET_NAME="power-oss-bucket" 
COS_OBJECT_NAME=capibm-powervs-centos-streams9-1-29-3-1719470782.ova.gz
```
