### ISSUE TITLE
Check how to delete master node

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#187]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

As the cluster controller was running on master node, so we may not able to delete master node based on steps here https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud#cluster-deletion .

@wanghh2000 can you please help check this?

FYI @jichenjc @xunpan @clyang82 @hchenxa

**Comment by hchenxa** [comment]
looks like same with https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/334.

**Comment by jichenjc** [comment]
yes, some discussion already there, should we allow this deletion or saftly ignore this cluster deletion (to me it's very unsafe as it's deleting itself...), do we encourage people to do so?

**Comment by gyliu513** [comment]
This is a use case for cluster api at https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/staging-use-cases.md#deleting-clusters 

Perhaps we do not need to mention delete master here, but delete cluster?

**Comment by jichenjc** [comment]
the reason is you will run the 'delete cluster' command on master
this is still delete itself command , I am ok to this as it's anyway need to be deleted but we need make sure this is safe and I doubt whether it will lead to orphan resource during some error case and lead to issues

**Comment by gyliu513** [comment]
@wanghh2000 please check if this works https://github.com/kubernetes-sigs/cluster-api/tree/master/cmd/clusterctl#deleting-a-cluster

**Comment by xunpan** [comment]
FYI: how deletion works
`clusterctl delete cluster` should pivot resources from target cluster to a bootstrap cluster and then delete cluster API resources to make local controller delete all VM instances. 

It should work based on my understanding. If there has any issue, please let me know. @wanghh2000

**Comment by jichenjc** [comment]
@xunpan 
I agree it might be the case if we are using the existing cluster, but for new provisoned one, this is not true.... see my provision log below 

I0528 02:49:01.520258    4302 clusterdeployer.go:154] Done provisioning cluster. You can now access your cluster with kubectl --kubeconfig kubeconfig
I0528 02:49:01.520408    4302 createbootstrapcluster.go:36] Cleaning up bootstrap cluster.
I0528 02:49:01.520424    4302 kind.go:69] Running: kind [delete cluster --name=clusterapi]
I0528 02:49:02.777023    4302 kind.go:72] Ran: kind [delete cluster --name=clusterapi] Output: Deleting cluster "clusterapi" ...

**Comment by xunpan** [comment]
I'm not sure what command line options you used. But it seems work in my environment. I use `kind` as boot strap cluster but not existing one.

This is my test result:
```
$ bin/clusterctl delete cluster -v 5 --bootstrap-type kind --kubeconfig kubeconfig  
-p cmd/clusterctl/examples/ibmcloud/out/provider-components.yaml
I0528 02:53:34.165970   19831 clusterdeployer.go:160] Creating bootstrap cluster
...
I0528 03:00:03.698059   19831 clusterclient.go:750] Waiting for Cluster API resources to have statuses...
I0528 03:00:13.698096   19831 clusterclient.go:750] Waiting for Cluster API resources to have statuses...
...
```
It hangs here, but the related resources had already deleted from target cluster.
```
$ kubectl --kubeconfig kubeconfig  get cluster
Error from server (NotFound): Unable to list "cluster.k8s.io/v1alpha1, Resource=clusters": the server could not find the requested resource (get clusters.cluster.k8s.io)
$ kubectl --kubeconfig kubeconfig  get machine
Error from server (NotFound): Unable to list "cluster.k8s.io/v1alpha1, Resource=machines": the server could not find the requested resource (get machines.cluster.k8s.io)
```
So, I think it should work. But, the deletion should have bug in IBM Cloud implementation.

**Comment by jichenjc** [comment]
this is my command ...

```
./clusterctl create cluster --bootstrap-type kind --provider ibmcloud   -c examples/ibmcloud/out/cluster.yaml -m examples/ibmcloud/out/machines.yaml   -p examples/ibmcloud/out/provider-components.yaml -v 10
```

and after creation complete
```
root@jichen1:/home/cloudusr/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# kubectl --kubeconfig=kubeconfig  get machines
NAME                  PROVIDERID              PHASE
jichen-master-g8wzd   ibmcloud:////81247881
jichen-node-ll257     ibmcloud:////81248367   Running
root@jichen1:/home/cloudusr/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# kind get clusters                         root@jichen1:/home/cloudusr/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl#
```

**Comment by xunpan** [comment]
@jichenjc 
We're **deleting** cluster I guess. It is different from `create` operation.

**Comment by jichenjc** [comment]
@xunpan you are right, I misunderstand some part 

now I have similar situation to you

I0528 07:58:48.015155   14233 clusterclient.go:750] Waiting for Cluster API resources to have statuses...

so there might be something wrong we need handle...

**Comment by jichenjc** [comment]
The cluster is gone , but the resource is still there, and there is no way to clear the machines unless we go to cloud portal and make changes.... this is unacceptable

jichen-master-g8wzd.example.com 
jichen-node-ll257.example.com

**Comment by jichenjc** [comment]
let me spend some time on this as this is important due to resource leak

**Comment by geosmart** [comment]
```bash
kubectl drain geolab.master --ignore-daemonsets
kubectl delete node geolab.master
kubeadm reset
```
