### ISSUE TITLE
Cannot login the machine with non-root user

### ISSUE THREAD

**Issue by clyang82** [kubernetes-sigs/cluster-api-provider-ibmcloud#192]
/kind bug
/sig ibmcloud

if configured `sshUserName: clyang` non-root user, it throws the following error when executing `./clusterctl create cluster ...`

```
I0527 23:02:08.090208   16305 deployer.go:51] Returning IP from machine annotation 108.168.190.94
E0527 23:02:12.916682   16305 util.go:178] error executing command "ssh -i /Users/clyang/.ssh/id_ibmcloud -o StrictHostKeyChecking no -o UserKnownHostsFile /dev/null -o BatchMode=yes clyang@108.168.190.94 echo STARTFILE; sudo cat /etc/kubernetes/admin.conf": exit status 255
I0527 23:02:18.093310   16305 deployer.go:51] Returning IP from machine annotation 108.168.190.94
E0527 23:02:21.912571   16305 util.go:178] error executing command "ssh -i /Users/clyang/.ssh/id_ibmcloud -o StrictHostKeyChecking no -o UserKnownHostsFile /dev/null -o BatchMode=yes clyang@108.168.190.94 echo STARTFILE; sudo cat /etc/kubernetes/admin.conf": exit status 255
I0527 23:02:28.093224   16305 deployer.go:51] Returning IP from machine annotation 108.168.190.94
E0527 23:02:34.631594   16305 util.go:178] error executing command "ssh -i /Users/clyang/.ssh/id_ibmcloud -o StrictHostKeyChecking no -o UserKnownHostsFile /dev/null -o BatchMode=yes clyang@108.168.190.94 echo STARTFILE; sudo cat /etc/kubernetes/admin.conf": exit status 255
I0527 23:02:38.089622   16305 deployer.go:51] Returning IP from machine annotation 108.168.190.94
```

**Comment by gyliu513** [comment]
@xunpan @jichenjc any comments for this?  I think SL API should also support non-root user.

**Comment by xunpan** [comment]
I think you should use a non-root user which works in the VM instance. E.g. `ubuntu`. 
Currently, cluster API does not create the user by `sshUserName` automatically.

**Comment by gyliu513** [comment]
@xunpan how can I know which user was supported in the VM instance?

**Comment by xunpan** [comment]
https://docs.openstack.org/image-guide/obtain-images.html
It tells each predefined image user accout.

**Comment by gyliu513** [comment]
Can we update the document a bit by adding this to troubleshooting? @xunpan @clyang82

**Comment by jichenjc** [comment]
@gyliu513 I agree with @xunpan 
The image will not support all user by default, maybe we need @clyang82 to help to find the default user id of IBM image, the image precreated is not able to create user we defined in cluster-api-xxx, and this is not best practice, so add some info in the document should be enough

**Comment by clyang82** [comment]
From [here](https://cloud.ibm.com/docs/vsi-is?topic=virtual-servers-is-images), we can see the SL support linux `CentOS`, `Debian`, `Redhat`, `Ubuntu`. I have tried with `CentOS_LATEST`, `DEBIAN_LATEST`, `REDHAT_LATEST`, `UBUNTU_LATEST`.  They can be logged with`root` user successfully. so suggest to hide `sshUserName` from the template file, it can be able to reduce the chances of errors. if there is no `sshUserName` defined, use `root` user to access. WDYT? @gyliu513 @jichenjc @xunpan

**Comment by jichenjc** [comment]
it's not a good practice to hide the user name ,e.g. ubuntu image sometimes only support 'ubuntu' user and no 'root' logon... I prefer to only document this kind of info instead omit ssh user , and omit ssh user might be more confusing.

**Comment by gyliu513** [comment]
@clyang82 How about keep `sshUserName` and set the default value as root plus some comments?

```
# comments for why we set it as root.
sshUserName: root
```

@jichenjc @xunpan WDYT?

**Comment by jichenjc** [comment]
works for me @gyliu513

**Comment by xunpan** [comment]
I think we need both. 
 - As IBM allows `root` and it works for all VM as @clyang82 tested, it can be default if there is no other security concerns. As what we did for memory and cpus. Both are preferred values.
 - Document it also needed. It should tell what kind of accout can be used in this field.

**Comment by clyang82** [comment]
Close it since PR was merged
