### ISSUE TITLE
tweak IbmcloudXX to IBMCloudXX for better UX

### ISSUE THREAD

**Issue by chenzhiwei** [kubernetes-sigs/cluster-api-provider-ibmcloud#193]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
where's the UI?? do we have UX?

**Comment by chenzhiwei** [comment]
The keyword is in YAML files, the YAML files is the interface to users.

**Comment by xunpan** [comment]
I agree with @chenzhiwei. `Ibm` seems not a word. `IBMCloud` should be better to export to end users.

**Comment by gyliu513** [comment]
@xunpan @chenzhiwei can you help check if `kubebuilder` support this? The kind like `IbmcloudMachineProviderSpec` are generated by `kubebuilder`.

**Comment by chenzhiwei** [comment]
/assign

I will take a look.

**Comment by chenzhiwei** [comment]
Seems the Kind is generated by `--kind Name`, so it is possible to generate by kubebuilder.
