### ISSUE TITLE
Validate DHCP server status before reusing existing DHCP network

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1933]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Today, If user sets spec.dhcpServer.name and while checking for network we assume that there might exist a network associated with the server. If the network exist we are simply considering it. Code ref: https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/blob/3eb2b524c65167565c595d01e475497b066ef22a/cloud/scope/powervs_cluster.go#L884-L891

The request is to validate the DHCP server status before considering the associated network.

Reconcile Network workflow

1. spec.DHCPserver.id is set - BUG, This case is not hanlded
		Comments:  Need to discuss what should be done on how to select network, may be expect network id to be set?

2. spec.DHCPServer.name is set 
	a. if spec.network.id is set - Fetch for network with id and use 
		Comments: DHCPServer name is ignored and network id got preference, 
	b. Try to find network with name DHCPSERVER<spec.DHCPServer.name>_Private and if found use

3. spec.DHCPServer.name is not set  
	a. if spec.network.id is set - Fetch for network with id and use 
		Comments: DHCPServer name is ignored and network id got preference, 

	*. if spec.network.name is set
		a. Try to find network with name spec.network.name

	*. if spec.network.name is not set 
	    a. Try to find network with name DHCPSERVER<cluster_name>_Private and if found use

4. If the network is not found, Create DHCP server with name spec.DHCPServer.Name if set else with clustername
	set both dhcpserverid and network id in status.

5. status.DHCPServer.id is set, then the dhcp server will be created by controller and status.network.id will also be set by controller

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Karthik-K-N** [comment]
@Amulyam24 @dharaneeshvrd also we cannot check DHCP server status when user provides name of existing network right, Because no where we can know, if it has associated DHCP server or not.
Just wanted to know is there any way we can validate a network is functional?

**Comment by Karthik-K-N** [comment]
@Amulyam24 we also need to check whats the flow when we set spec.network.name.

**Comment by Karthik-K-N** [comment]
What will happen when a user sets a network name in spec say "capiNetwork" and which does not exist in cloud, 

I think currently controller does following things, 
1. Tries to fetch network in cloud with name "capiNetwork", Which does not exist so returns nil
2. The dhcp network will be created, but the dhcp network name wont be same as user provided as we dont have control over full network name created by DHCP server.

@dharaneeshvrd I think we need to handle this case right?

**Comment by dharaneeshvrd** [comment]
Yes Agree. We have to handle that case.
