### ISSUE TITLE
release-0.8 documentation link is broken

### ISSUE THREAD

**Issue by Amulyam24** [kubernetes-sigs/cluster-api-provider-ibmcloud#1939]
/kind bug
/area provider/ibmcloud

This issue is to track and fix the documentation link for release-0.8. branch. 
https://main.cluster-api-ibmcloud.sigs.k8s.io
https://release-0-8.cluster-api-ibmcloud.sigs.k8s.io

This has a dependency and need help from [kubernetes/org](https://github.com/kubernetes/org) team

Previous issue: https://github.com/kubernetes/org/issues/4983

**Comment by Amulyam24** [comment]
Created another issue - https://github.com/kubernetes/org/issues/5136

**Comment by Prajyot-Parab** [comment]
Resolved.
/close
