### ISSUE TITLE
Improve transit gateway status usage

### ISSUE THREAD

**Issue by dharaneeshvrd** [kubernetes-sigs/cluster-api-provider-ibmcloud#1960]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
With current implementation there are few scenarios are not handled properly
- When TG is created properly and there is a error while creating the connection means status won't be stored but connection would have been created and on next reconciliation it would be processed by existing resource case which should not happen.
- It's best to store the status separately immediately after processing the resources.
- Also improve the usage of Transit Gateway's status overall.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkumatag** [comment]
@dharaneeshvrd I see #1961 already merged, do you want to fix anything else part of this issue?

**Comment by dharaneeshvrd** [comment]
No, we can close it.
