### ISSUE TITLE
No explanation for how to edit yaml files for create cluster 

### ISSUE THREAD

**Issue by wanghh2000** [kubernetes-sigs/cluster-api-provider-ibmcloud#197]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
Following doc to create cluster and no details about how to edit cluster.yaml and machines.yaml

**What did you expect to happen:**
Some explanation about values in yaml file.

**Anything else you would like to add:**

**Environment:**

- Cluster-api version: mainline
- Minikube/KIND version:  kind 0.3.0
- Kubernetes version: (use `kubectl version`): 1.14
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by clyang82** [comment]
more specific - `osReferenceCode` is hard to understand. Should we name it as `image`?

/cc @gyliu513 @jichenjc comments?

**Comment by xunpan** [comment]
The IBM Cloud softlayer uses "operatingSystemReferenceCode" as arguments.
This is programming interface. I think it is not friendly to end users.

Could you please help to check how IBM Cloud (softlayer) uses this value and document it for end users? We should better use consistent term for it.

**Comment by gyliu513** [comment]
@clyang82 already have document here https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/docs/ibmcloud_help.md#how-to-set-correct-os-reference-code-in-machinesyaml

**Comment by wanghh2000** [comment]
This is what I get from there https://softlayer-api-python-client.readthedocs.io/en/latest/cli/hardware/#hw-create. Not sure if it is the same.
