### ISSUE TITLE
[Question]how to use the clusterctl validate cluster

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-ibmcloud#199]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

clusterctl provide a command which used to check the cluster healthy with `clusterctl validate cluster`

but the command behavior was after the master provided, the bootstrap node will be deleted, so the question is, how to use this command to check my cluster? did I need to manually copy the binary to all deployed k8s cluster?

cc @xunpan @gyliu513 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by xunpan** [comment]
The `bootstrap cluster` is deleted. But the binary should be on your `bootstrap host`.
So, the `clusterctl` exsits for your use.

**Comment by jichenjc** [comment]
I got this 

```
root@jichen1:/home/cloudusr/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# ./clusterctl --kubeconfig=kubeconfig validate cluster
Validating Cluster API objects in namespace ""
Checking cluster object "test1"... PASS
Checking machine object "jichen-master-6s8px"... FAIL
        The corresponding node is missing.
Checking machine object "jichen-node-4qvwl"... FAIL
        The corresponding node is missing.
ERROR: machine objects failed the validation

```

**Comment by jichenjc** [comment]
the bootstrap cluster is gone in my above test, so no need to copy the binary just use the kubeconfig..

**Comment by xunpan** [comment]
The `validation` should be failed because we did not fully support it until now.

**Comment by jichenjc** [comment]
opened https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/200 to track
