### ISSUE TITLE
Enable daily build on master

### ISSUE THREAD

**Issue by clyang82** [kubernetes-sigs/cluster-api-provider-ibmcloud#202]
/kind bug
/sig ibmcloud

Right now, we have some code changes on master branch so that the v0.0.1 image cannot be working. we have to setup the daily build on master.

FYI @gyliu513 @jichenjc

**Comment by xunpan** [comment]
Is this duplidated of https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/154?

**Comment by clyang82** [comment]
Close it since the PR was merged.
