### ISSUE TITLE
quay.io report some VA errors for latest controller

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#209]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

![image](https://user-images.githubusercontent.com/4461983/58686692-11596780-83b2-11e9-89bc-518d490b1f97.png)

@wanghh2000 can you help check?

**Comment by jichenjc** [comment]
I thought we fixed the bug ?? https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/204

**Comment by wanghh2000** [comment]
I will check.

**Comment by wanghh2000** [comment]
![image](https://user-images.githubusercontent.com/7058900/58687704-f805ea80-83b4-11e9-8253-69f794c1ae58.png)

**Comment by clyang82** [comment]
@gyliu513 I just manually triggered the ci build to generate the latest image. @wanghh2000 's picture is latest.

**Comment by wanghh2000** [comment]
Fixed by #204. 
Test again passed.
