### ISSUE TITLE
Flaky test: TestIBMPowerVSClusterReconciler_reconcile/When_reconcile_VPC_and_PowerVS_resource_returns_error

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#2097]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
for more information:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/2071/pull-cluster-api-provider-ibmcloud-coverage/1866029141204144128#1:build-log.txt%3A250
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/2072/pull-cluster-api-provider-ibmcloud-coverage/1864603198640099328#1:build-log.txt%3A248

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Karthik-K-N** [comment]
@Shilpa-Gokul Could you please take care of this, I think we should ignore the error order here https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/blob/c4171f21acc320fdfe17b812c98be908653134f7/controllers/ibmpowervscluster_controller_test.go#L504, 
Please see if there is any better matcher than Equal https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/blob/c4171f21acc320fdfe17b812c98be908653134f7/controllers/ibmpowervscluster_controller_test.go#L720.

Or is there any better way also. Thanks
