### ISSUE TITLE
clusterctl support in cluster mode

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-ibmcloud#212]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

as we already provide the clusterctl docker image, so I can run the clusterctl with pod in an kubernetes as well, if the command running in a pod, it's better to support in cluster mode so that it can use the current k8s cluster to deploy the machines.

cc @gyliu513 @clyang82 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by xunpan** [comment]
@hchenxa Could you please help to share potential use case for this?

**Comment by hchenxa** [comment]
@xunpan , their have one case like:

I was using tekton to create a pipeline and the first task was use cluster-api to create the cluster, so the clusterctl will be running in pod. in this case, as I already have the existing kubernetes info and the service account which can connect to api server, so I just need to use these info to connect the existing cluster but not to use kind to create the new one.
