### ISSUE TITLE
SSH Copy of admin.conf breaks

### ISSUE THREAD

**Issue by hwinkel** [kubernetes-sigs/cluster-api-provider-ibmcloud#216]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**

./clusterctl command as in the README. runs fine upt to the ssh command
trying to fetch the (etc/kubernetes/admin.conf

SSH Command breaks

`E0602 23:46:54.082651    8578 util.go:178] error executing command "ssh -i /Users/hwinkel/.ssh/id_ibmcloud -o StrictHostKeyChecking no -o UserKnownHostsFile /dev/null -o BatchMode=yes ubuntu@1.2.3.4 echo STARTFILE; sudo cat /etc/kubernetes/admin.conf": exit status 1`

The syntax for the options is wrong its missing the "=" for the StrictHostkeyChecking and UserKnownHostFile option.

However, running it manually with corrected options the host still asks for passwd login. Without the options the command works and i have interactive SSH login without password:

`ssh -i /Users/hwinkel/.ssh/id_ibmcloud  root@1.2.3.4 `

**What did you expect to happen:**

./clusterctl command runs to completion

**Anything else you would like to add:**
Running Stock MacOS SSHClient OPenSSH. 

**Environment:**

- Cluster-api version:
- Minikube/KIND version: not used, used external cluster 1.4.2
- Kubernetes version:1.4.2
- OS: MacOS 10.14.5

**Comment by xunpan** [comment]
@hwinkel 
It is not madatory to have `=` in the option. 

Could you please help to check:
1. did you create ssh key with correct public key corresponding to ~/.ssh/id_ibmcloud which is generated during running script `fenerate-yaml.sh`? The public key name should be `id_rsa_ibmcloud.pub`. You should use the content of it to create ssh key in IBM Cloud.
2. in `machines.yaml`, you set `sshKeyName:` with created ssh key in IBM cloud.

From your log, it seems you're using someting like `id_rsa.pub` to create ssh in IBM Cloud. 
Please help to have a check and let me know if it works or not.

**Comment by jichenjc** [comment]
>>.running it manually with corrected options the host still asks for passwd login.
this means likely the ssh key password is not created and injected into VM correctly, as xun mentioned, please check ssh key creation and try again, you may see some error log but it's a periodic loop and it should success after several loops

**Comment by hwinkel** [comment]
No, a normal login shell (without all the options) works just fine if i use
ssh -i /Users/hwinkel/.ssh/id_ibmcloud  ubuntu|root@1.2.3.4. I get a login shell, the d_ibmcloud.pub is deployed correctly.

regardless of the "=" or not. (i have read the same) it should be consistent. Don'T know the OPenSSH on the mac does something different here. If I run the command with the "=" from command line it at least stops erroring on the command self. But still asks for password, wich is somehow strange, as it works without the -o option.

I would further rather prefer to run theses commands from within the pods?

**Comment by xunpan** [comment]
@hwinkel 
It can run without pod.

I agree it should be consistent. It is should be helpful in debug. I will fix it. But it is not funcational. For your issue, need password for ssh, I'd like to know what happens exactly to understand it.

With or without `=` is fine as `-o` format for openssh. It is documented in `openssh` man page.
```
     Configuration options may be separated by
     whitespace or optional whitespace and exactly one `='; the latter format
     is useful to avoid the need to quote whitespace when specifying configu-
     ration options using the ssh, scp, and sftp -o option.
```

My test:
```
$ ssh -i id_ibmcloud -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -o BatchMode=yes root@<your.ip.address> hostname
a-xun-ibmcloud-master-98n2c
$ ssh -V
OpenSSH_7.9p1, LibreSSL 2.7.3
```

**Comment by jichenjc** [comment]
yes, I think you the format is not the problem, there should be something wrong in ssh key pair setting

maybe check following 2 things :
1) check whether the private/public key is 0600/0400 mode 
2) check whether you copied the file `/Users/hwinkel/.ssh/id_ibmcloud` but there is another public key `/Users/hwinkel/.ssh/id_ibmcloud.pub` in same folder but not the exact public key it created (which is, you use another private key to overwrite /Users/hwinkel/.ssh/id_ibmcloud) 

I encountered those 2 before and lead to simliar situation you had,let's try this or paste the ssh key setting you are using and private/public key seting for further check

**Comment by xunpan** [comment]
@hwinkel  any information for sharing?
