### ISSUE TITLE
Upgrade Cluster API to 0.1.1

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#221]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

This can enable us to use the feature of multiple control plane support https://github.com/kubernetes-sigs/cluster-api/compare/0.1.1...master

Related to https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/161

FYI @xunpan @jichenjc 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
@jichenjc seems we do not need to upgrade, and release-0.1.0 already include the fix based on comments here https://github.com/kubernetes-sigs/cluster-api/pull/878#issuecomment-498678918

**Comment by jichenjc** [comment]
yes, I noticed that, the action is to consider how to consume that change now..

**Comment by xunpan** [comment]
I think we can close this ticket. We've already have it after https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/61

**Comment by jichenjc** [comment]
we should have this now in our vendor subfolder ,so we can close this 
https://github.com/kubernetes-sigs/cluster-api/pull/878/files
