### ISSUE TITLE
Adding KIND to clusterctl docker image

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#222]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

This can help to facilitate the process of provisioning k8s cluster with KIND.

FYI @clyang82 @hchenxa 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by hchenxa** [comment]
@gyliu513 , based on https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/212, if we support in-cluster mode to use the existing cluster, I did not think that we should package kind in the docker image.

**Comment by gyliu513** [comment]
@hchenxa as using existing cluster need to do some clean up after cluster install finished, like some CRD etc. We can package KIND now to have a simple way to install.

**Comment by hchenxa** [comment]
we have package the kind in docker with clusterctl packaged and @zxdiscovery@gmail.com was do testing these days. 

cc @clyang82

**Comment by gyliu513** [comment]
I opened an issue at https://github.com/kubernetes-sigs/cluster-api/issues/981 to let cluster-api can use random name for bootstrap cluster.
