### ISSUE TITLE
prefer to have a yaml sample to deploy the cluster within pod

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-ibmcloud#226]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

we have package kind and docker client in clusterctl docker image, so it's prefer to have a yaml file which can be used to deploy cluster within pods.

cc @gyliu513 @zxDiscovery @clyang82 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gyliu513** [comment]
@zxDiscovery can provide both document and yaml file to fix this.
