### ISSUE TITLE
Cannot delete the cluster created by kind

### ISSUE THREAD

**Issue by clyang82** [kubernetes-sigs/cluster-api-provider-ibmcloud#227]
/kind bug
/sig ibmcloud

We have packed kind and docker client in clusterctl docker image. it is available in latest version - quay.io/cluster-api-provider-ibmcloud/clusterctl:latest

When I use a sample job to create the cluster, the kind cluster cannot be deleted once there has any errors.  You have to login the worker node to install the kind client to delete the cluster in order to rerun the job.

/cc @gyliu513 @hchenxa @zxDiscovery

**Comment by xunpan** [comment]
Did you try `kind delete cluster --name=clusterapi` manually in your container started by `clusterctl` image? It is used by `clusterctl` to delete kind cluster when there has issues during cluster creation.

**Comment by hchenxa** [comment]
or you may delete the containers which create by kind on your work node. execute below commands to find the container you created:
`docker ps -qa --no-trunc --filter "label=io.k8s.sigs.kind.cluster=<clustername>"`

**Comment by clyang82** [comment]
Thanks @xunpan @hchenxa for your solution. I think we may add the delete kind cluster before the job exists unexpectedly.

**Comment by gyliu513** [comment]
@clyang82 https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/249

FYI @songleo

**Comment by hchenxa** [comment]
I prefer to open this issue and I think it's not prefer to install the kind of each of worker node and manually delete the cluster before create this yaml.

**Comment by gyliu513** [comment]
@hchenxa when upgrade cluster api, we will have random cluster name https://github.com/kubernetes-sigs/cluster-api/pull/984 , so there will not be such problem.

**Comment by hchenxa** [comment]
@gyliu513 , so there have a new problem when using the random cluster name, if the job failed, we did not clean up the kind cluster, so there will have so many kind cluster created on the worker node.

**Comment by gyliu513** [comment]
@hchenxa , that's a question and you can open another issue to trace it.
