### ISSUE TITLE
Can not build clusterctl

### ISSUE THREAD

**Issue by dongwangdw** [kubernetes-sigs/cluster-api-provider-ibmcloud#229]
/kind bug
/sig ibmcloud

```
 k8s.io/client-go/rest
/root/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)

```
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I just cloned the cloudctl as the readme states.

**What did you expect to happen:**
cloudctl can be built successfully or `go build` is good.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
os: ubuntu 18.06, AMD64.
go: 12.5

**Comment by dongwangdw** [comment]
For more info about my kubectl:
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-17T00:58:35Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by dongwangdw** [comment]
I found this #https://github.com/gruntwork-io/terratest/issues/276. I changed my the version of go-client. But no help.

**Comment by gyliu513** [comment]
Your `GOPATH` is not right.

```
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud# cd cmd/clusterctl
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# ls
Dockerfile  clusterctl  examples  kubeconfig  main.go
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# go build
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# ls -l
total 47132
-rw-r--r-- 1 root root     1526 Jun  9 05:40 Dockerfile
-rwxr-xr-x 1 root root 48242533 Jun  9 05:41 clusterctl
drwxr-xr-x 3 root root     4096 Apr 30 02:38 examples
-rw-r----- 1 root root     5450 May  7 06:38 kubeconfig
-rw-r--r-- 1 root root      741 Apr 29 18:35 main.go
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# date
Sun Jun  9 05:41:19 PDT 2019
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# go version
go version go1.12.5 linux/amd64
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl# env | grep GO
GOPATH=/root/go
```

**Comment by wanghh2000** [comment]
Run `env` and append the output could help trouble shooting.

**Comment by dongwangdw** [comment]
My GOPATH is `/root/go/`.  I tried again, and now I got this. Did I miss anything?

root@wangdong1 ~/g/s/s/cluster-api-provider-ibmcloud# pwd
/root/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud
root@wangdong1 ~/g/s/s/cluster-api-provider-ibmcloud# echo $GOPATH
/root/go
root@wangdong1 ~/g/s/s/cluster-api-provider-ibmcloud# cd cmd/clusterctl/
root@wangdong1 ~/g/s/s/c/c/clusterctl# ls
Dockerfile  examples/  main.go
root@wangdong1 ~/g/s/s/c/c/clusterctl# go build
go: finding k8s.io/api/admissionregistration/v1alpha1 latest
go: finding k8s.io/api/admissionregistration latest
go: finding k8s.io/api latest
**build sigs.k8s.io/cluster-api-provider-ibmcloud/cmd/clusterctl: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package** k8s.io/api/admissionregistration/v1alpha1
root@wangdong1 ~/g/s/s/c/c/clusterctl# go version
go version go1.12.5 linux/amd64
root@wangdong1 ~/g/s/s/c/c/clusterctl# date
Sun Jun  9 07:05:04 PDT 2019
root@wangdong1 ~/g/s/s/c/c/clusterctl#

**Comment by gyliu513** [comment]
@wanghh2000 can you help check @dongwangdw 's env to see what is wrong?

**Comment by wanghh2000** [comment]
@dongwangdw Did you have a difference version code under Path /root/go/src/k8s.io  or GO/src/k8s.io?

**Comment by dongwangdw** [comment]
I got another machine which can build it without any problem. Same os, same go version and same kubectl version.

**Comment by wanghh2000** [comment]
Seems environment issue.

**Comment by xunpan** [comment]
Please close this ticket if it is not a `cluster-api-provider-ibmcloud` issue. @dongwangdw

**Comment by xunpan** [comment]
Please open it if it matters to you.
