### ISSUE TITLE
Create loadbalancer inside ibmcloud

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-ibmcloud#230]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
this is needed for some use case such as multiple master 
https://kubernetes.io/docs/setup/independent/high-availability/

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
FYI @xunpan

**Comment by xunpan** [comment]
For `softlayer.com`, it seems we have no permission or even cannot be permitted to create LB. So, you may need to use `www.ibm.com/cloud`.

**Comment by jichenjc** [comment]
Thanks for the reminder.. the question is , do we have access to IBM cloud? I remember I tried before but doesn't work , anyone knows about it ?@xunpan @gyliu513

**Comment by gyliu513** [comment]
@jichenjc Can you help post a question to #sig-ibm-cloud and ask this?
