### ISSUE TITLE
switch from cloud-init based scripts template to kubeadm API generated scripts

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-ibmcloud#231]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

we are using a template (cloud-init) for kubeadm startup scripts now, this is easy but not that flexible, in the long run, we may consider to switch to https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/master/pkg/cloud/aws/services/kubeadm in order to make it more easier for to do coding development instead of manually modify the template

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
@gyliu513 @xunpan  FYI

**Comment by xunpan** [comment]
Could you help to explain a little more about what is it? And how it works?

**Comment by jichenjc** [comment]
please refer to what aws did, seems they are using kubeadm library instead of just use template such as yaml to build kubeadm config file and scripts, I believe using the kubeadm library provides more flexiblity ,e.g when you do multi controller, options such as JoinConfigurationOption  will be helpful

during openstack summit someone ( not remember the name) also asked me about the same question on openstack provider
