### ISSUE TITLE
Refactor ibm cloud provider use go module

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-ibmcloud#235]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md
noticed this, should we follow this or keep using dep or take this a future action?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by xunpan** [comment]
I think keep consistent with cluster-api is fine.
`go module` should be future direction as it is official go dependecy management tool. However, currently, there is no painpoint for using `dep` in ibm cloud provider. When cluster-api switch its dependecy management tool. We can follow it up.

**Comment by jichenjc** [comment]
ok, let's take this as future item

**Comment by gyliu513** [comment]
cluster api is working for this https://github.com/kubernetes-sigs/cluster-api/pull/1054#issuecomment-504276869

**Comment by jichenjc** [comment]
Thanks, I am looking at it and hopefully to replicate to here soon...

**Comment by jichenjc** [comment]
/assign 

let me try this

**Comment by gyliu513** [comment]
/remove-lifecycle stale

@jichenjc do you still have plan to work for this? I think we need to take this as priority now.

**Comment by jichenjc** [comment]
@gyliu513 I am buried in some other stuffs recently, so unassign myself and let's see anyone can help on this, thanks for the reminder

**Comment by gyliu513** [comment]
/assign 

Thanks @jichenjc for the heads up, let me check this.
