### ISSUE TITLE
SIG IBMCloud is moving as a sub-project of Cloud Provider SIG

### ISSUE THREAD

**Issue by spzala** [kubernetes-sigs/cluster-api-provider-ibmcloud#269]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
All the current cloud provider sigs are moving as sub-projects of the SIG Cloud Provider. You can find the changes that are under review and mostly agreed upon here - https://github.com/kubernetes/community/pull/3895 Once this PR is merged, we need to rename SIG IBMCloud as sub-project cloud-provider-IBMCloud (or a new name if that's what decided in the above PR). Also, the `sig-ibmcloud-leads` will be removed so we should move the listed folks there under `cluster-api-ibmcloud-reviewers`. I am opening this request as heads up, and will update info here once the above mentioned PR is merged. Thanks! /cc @gyliu513

**Comment by gyliu513** [comment]
Thanks @spzala , assign this to you for a PR. ;-)

**Comment by jichenjc** [comment]
sorry, cluster-api is different to cloud-provider, I understand cloud-provider is in cloud-proivder SIG
and seems cluster-api doesn't belong to cloud-provider SIG as far as I can tell..... 
@spzala

**Comment by spzala** [comment]
> Thanks @spzala , assign this to you for a PR. ;-)

LOL sounds good @gyliu513

**Comment by spzala** [comment]
> sorry, cluster-api is different to cloud-provider, I understand cloud-provider is in cloud-proivder SIG
> and seems cluster-api doesn't belong to cloud-provider SIG as far as I can tell.....
> @spzala

I agree about differences but at the same time all the projects from cloud providers are owned by their SIG. Like, cluster-api-provider-ibmcloud was created as a sub-project of IBM Cloud SIG. But there is a related ongoing discussion and we will make changes accordingly. For now, as in the PR I mentioned above you can see the following comment, 
```
Yep, in the proposal, we mention that each provider would migrate in as provider-<provider>, with the associated [sub-]subprojects within e.g.,

provider-azure

    https://raw.githubusercontent.com/kubernetes/cloud-provider-azure/master/OWNERS
    https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/master/OWNERS
```
Thanks!

**Comment by spzala** [comment]
@gyliu513 fyi, `sig/ibmcloud` label is now renamed to `area/provider/ibmcloud `

**Comment by gyliu513** [comment]
@spzala thanks for the info, do you know what kind of CLI that I should run if I want to add the label `area/provider/ibmcloud`, I was using `/sig ibmcloud` before.

**Comment by spzala** [comment]
@gyliu513 hi, `/area provider/ibmcloud` should do it, can you please try it? Thanks!
