### ISSUE TITLE
LeaderElectionID should be unique

### ISSUE THREAD

**Issue by noamran** [kubernetes-sigs/cluster-api-provider-ibmcloud#279]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
This issue was reported in other providers - Running several Cluster API pods (e.g. CAPI + CABPK + an infra provider) in the same namespace results in leader election errors. 
Additional details here - kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#271

**Comment by gyliu513** [comment]
@songleo

**Comment by jichenjc** [comment]
FYI: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/478
