### ISSUE TITLE
upgrade cluster-api to 0.3.8

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/cluster-api-provider-ibmcloud#296]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
@xunpan this need move to cluster-api v1alpha3 , a big change ahead :)
