### ISSUE TITLE
PowerVS support

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#299]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
This task is to add the support for IBMCloud PowerVS, includes following items:

1. Image preparation - https://image-builder.sigs.k8s.io/capi/capi.html
2. Design and implementation(code)

**References:**
API Doc: https://cloud.ibm.com/apidocs/power-cloud
Go Client: https://github.com/IBM-Cloud/power-go-client
IBM Cloud catalog link: https://cloud.ibm.com/catalog/services/power-systems-virtual-server

**Comment by jichenjc** [comment]
I heard PowerVS comes from PowerVC, not sure it's true of not 
so will powervs shares same API to IBM Cloud or PowerVC?

**Comment by mkumatag** [comment]
> I heard PowerVS comes from PowerVC, not sure it's true of not
> so will powervs shares same API to IBM Cloud or PowerVC?

We can use the IBM Cloud APIs for accessing the PowerVS, here is the documentation - https://cloud.ibm.com/apidocs/power-cloud, and SDK - https://github.com/IBM-Cloud/power-go-client

**Comment by jichenjc** [comment]
> 
> 
> > I heard PowerVS comes from PowerVC, not sure it's true of not
> > so will powervs shares same API to IBM Cloud or PowerVC?
> 
> We can use the IBM Cloud APIs for accessing the PowerVS, here is the documentation - https://cloud.ibm.com/apidocs/power-cloud, and SDK - https://github.com/IBM-Cloud/power-go-client

thanks for the info~

**Comment by clnperez** [comment]
Should this be cluster-api-provider-powervs though? The plan isn't to encompass all of IBM Cloud, but to use the Power VS provisioning features provided by the IBM Cloud APIs, IIUC. Maybe not to quibble over just the name, but, get clarity on intent/focus.

**Comment by jichenjc** [comment]
@clnperez maybe you can check 
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/314

**Comment by clnperez** [comment]
Actually @jichenjc, @mkumatag cleared this up for me. IIUC, this issue is a request to get support for _Power VS_ added into `cluster-api-provider-ibmcloud`. But thanks!
