### ISSUE TITLE
Setup CI test for IBM VPC gen2 implementation

### ISSUE THREAD

**Issue by wentao-zh** [kubernetes-sigs/cluster-api-provider-ibmcloud#300]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
There is no CI test for IBM Cloud VPC gen2 implementation. We need to add test case to cover it.

**Anything else you would like to add:**
none

**Comment by wentao-zh** [comment]
The current ProwJob definition is out of date. I have updated presubmit for cluster-api-provider-ibmcloud and submited a PR.
https://github.com/kubernetes/test-infra/pull/20625

And added ci related script under https://github.com/wentao-zh/cluster-api-provider-ibmcloud/tree/ibmvpccloud/scripts
@jichenjc @gyliu513

**Comment by jichenjc** [comment]
seems some error occured https://github.com/kubernetes/test-infra/pull/20625
once all error fixed, we can merge and move forward.. thanks :)
