### ISSUE TITLE
Add design doc for VPC implementation

### ISSUE THREAD

**Issue by wentao-zh** [kubernetes-sigs/cluster-api-provider-ibmcloud#301]
/kind feature
/area provider/ibmcloud

We need to add design doc for current VPC gen2 implementation

**Comment by jichenjc** [comment]
yes, I am interested in this :)

**Comment by gyliu513** [comment]
design is at https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/ibmvpccloud/docs/proposal/architecture_for_diff_iaas.md
