### ISSUE TITLE
high version of kubeadm api is not applicable in cluster-api

### ISSUE THREAD

**Issue by wentao-zh** [kubernetes-sigs/cluster-api-provider-ibmcloud#303]
/kind bug
/area provider/ibmcloud

kubeadm bootstrap provider in cluster-api is using kubeadm.k8s.io/v1beta1
So that means high version of kubeadm can’t work correctly. Because it will report that configuration file uses a deprecated API spec and require to use kubeadm config migrate to translate from kubeadm.k8s.io/v1beta1 to kubeadm.k8s.io/v1beta2.
**What steps did you take and what happened:**

**What did you expect to happen:**
Make sure the provider can handle hight version of kubeadm api.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
have you reported this to `cluster-api` project for further comments? 
looks like this is general item for all cluster-api projects

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/types/v1beta2/types.go
is v1beta2 

so you might want to upgrade from there ..

**Comment by emmayang** [comment]
This issue is fixed by PR https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/309 and can be closed.
