### ISSUE TITLE
Specified --control-plane-machine-count=3 but only one master node was created

### ISSUE THREAD

**Issue by wentao-zh** [kubernetes-sigs/cluster-api-provider-ibmcloud#305]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
The rendered yaml show that the replicas of KubeadmControlPlane is 3. But only 1 machine and 1 ibmvpcmachine were created.

**What did you expect to happen:**
3 Machines should be created for k8s master

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
do you create Loadbanalcer ? otherwise how to create 3 masters?

**Comment by amycuicui** [comment]
Error log in pod capi-kubeadm-control-plane-controller-manager:
I0316 08:00:32.885106       1 controller.go:355] controllers/KubeadmControlPlane "msg"="Scaling up control plane" "cluster"="ibm-vpc-1" "kubeadmControlPlane"="ibm-vpc-1-control-plane" "namespace"="default" "Desired"=3 "Existing"=1
I0316 08:00:32.885249       1 scale.go:206] controllers/KubeadmControlPlane "msg"="Waiting for control plane to pass preflight checks" "cluster"="ibm-vpc-1" "kubeadmControlPlane"="ibm-vpc-1-control-plane" "namespace"="default" "failures"="[machine ibm-vpc-1-control-plane-6j62t does not have APIServerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have ControllerManagerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have SchedulerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have EtcdPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have EtcdMemberHealthy condition]"
I0316 08:00:48.397949       1 controller.go:244] controllers/KubeadmControlPlane "msg"="Reconcile KubeadmControlPlane" "cluster"="ibm-vpc-1" "kubeadmControlPlane"="ibm-vpc-1-control-plane" "namespace"="default" 
I0316 08:00:49.757972       1 controller.go:355] controllers/KubeadmControlPlane "msg"="Scaling up control plane" "cluster"="ibm-vpc-1" "kubeadmControlPlane"="ibm-vpc-1-control-plane" "namespace"="default" "Desired"=3 "Existing"=1
I0316 08:00:49.758168       1 scale.go:206] controllers/KubeadmControlPlane "msg"="Waiting for control plane to pass preflight checks" "cluster"="ibm-vpc-1" "kubeadmControlPlane"="ibm-vpc-1-control-plane" "namespace"="default" "failures"="[machine ibm-vpc-1-control-plane-6j62t does not have APIServerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have ControllerManagerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have SchedulerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have EtcdPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have EtcdMemberHealthy condition]"

**Comment by jichenjc** [comment]
looks like 
```
machine ibm-vpc-1-control-plane-6j62t does not have APIServerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have ControllerManagerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have SchedulerPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have EtcdPodHealthy condition, machine ibm-vpc-1-control-plane-6j62t does not have EtcdMemberHealthy condition]"
```

have you login 2nd and 3rd master to check what happened there?

**Comment by amycuicui** [comment]
I added the conditions to controlplane controller, but it does not work.
From the cluster-api source code, seems the conditions are not directly added by our code.

**Comment by andyzheung** [comment]
Is this problem solved?
I am also meet this problem 
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1700
