### ISSUE TITLE
The current customized image only support k8s v1.14.3

### ISSUE THREAD

**Issue by wentao-zh** [kubernetes-sigs/cluster-api-provider-ibmcloud#306]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Need to provide more customized images to support different k8s versions and make it public accessable.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
you might want to check https://github.com/kubernetes-sigs/image-builder
