### ISSUE TITLE
Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail

### ISSUE THREAD

**Issue by diegocn** [kubernetes-sigs/cluster-api-provider-ibmcloud#323]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
After successfully started a Kubernetes cluster using cluster-api-provider-ibmcloud I've tried to create a `Service` of type `LoadBalancer` to expose a simple nginx `Deployment`. But I got this `Service` in the pending state.

Looking at the logs (kubectl cluster-info dump) I got this message related to LoadBalancers.

`E0526 21:25:22.208860       1 core.go:90] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail`

**What did you expect to happen:**
I would expect that the Kubernetes cluster created using IBM Cloud provider would be set to use IBM Cloud resources, like the LoadBalancer.

**Environment:**

- Cluster-api version: 0.3
- Minikube/KIND version: $ kind version -> kind v0.9.0 go1.15.2 linux/amd64 
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): LMDE 4 (debbie)

**Comment by mkumatag** [comment]
Usually the external LB service will work if the cloud-control-manager which is not handled via this repo, but still keeping this open to see how the integration can be done.

**Comment by mkumatag** [comment]
Will be taken care via #449
