### ISSUE TITLE
Fail to deploy cluste with latest capi.

### ISSUE THREAD

**Issue by dongwangdw** [kubernetes-sigs/cluster-api-provider-ibmcloud#325]
I just use the latest cluster api to deploy cluste against ibmcloud.
But the cluster is pending:
```
NAME        PHASE
ibm-vpc-0   Provisioning
```

As I found from the log of capi-system pod I got
```
controller.go:302] controller-runtime/manager/controller/cluster "msg"="Reconciler error" 
"error"="cannot find any versions matching contract \"cluster.x-k8s.io/v1alpha4\" for CRD ibmvpcclusters.infrastructure.cluster.x-k8s.io as contract version label(s) are either missing or empty"
"name"="ibm-vpc-0" 
"namespace"="default" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster"
```

**Comment by dongwangdw** [comment]
As I found the process in the readme is for api of cluster-api  "cluster.x-k8s.io/v1alpha3". 
But the latest version is v1alpha4. So I think this shoud be updated.

**Comment by jichenjc** [comment]
yes, I assume use latest cluster-api + v1alpha3 provider might have some problem 
maybe you can try cluster-0.3.x version

**Comment by mkumatag** [comment]
try the recent code now, we have pushed v1alpha4 apis

**Comment by mkumatag** [comment]
I'm closing the issue for now, lets open a new issue if there are still issues.
/close
