### ISSUE TITLE
flaky golangci-lint in the CI

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#356]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
seen golangci-lint is flaking in the CI, e.g: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/355/pull-cluster-api-provider-ibmcloud-test/1448978218232057856

**What did you expect to happen:**
shouldn't flake

**Anything else you would like to add:**
test is flaking due to timeout, need to explore how to bump the timeout for the linting.

**Comment by Amulyam24** [comment]
> I see a file `.golangci.yml` used in all the projects with that timeout mentioned, wondering if we can also use the similar config file to have better linting?! e.g: https://github.com/kubernetes-sigs/cluster-api/blob/main/.golangci.yml

+1 for using `.golangci.yml`. It would give us a defined control over linting.
