### ISSUE TITLE
cherrypick is not working

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#453]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
`/cherrypick` command is not working for the repo, need to check if any additional configuration needs to be made in the test-infra repository

e.g: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/452#issuecomment-987493759

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag Looks like we need to add ` cluster-api-provider-ibmcloud` with cherrypicker details to the list of external_plugins.
Like https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml#L1235:L1240
Shall submit a PR for it.

**Comment by mkumatag** [comment]
> @mkumatag Looks like we need to add ` cluster-api-provider-ibmcloud` with cherrypicker details to the list of external_plugins.
> Like https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml#L1235:L1240
> Shall submit a PR for it.

lets do that!

**Comment by mkumatag** [comment]
Thanks @Rajalakshmi-Girish for a quick fix, it is working fine now 🎉
