### ISSUE TITLE
Post run job from release-0.1 branch

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#464]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Haven't see image built/pushed for the postsubmit job on the release-0.1 branch and see if any prow job config needs to be added for that.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/assign @Rajalakshmi-Girish

**Comment by mkumatag** [comment]
It did run via this [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-ibmcloud-push-images/1468221772821172224) but the tag of the image was wrong I feel

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag Are we still not seeing `post-cluster-api-provider-ibmcloud-push-images` for `release-0.1 branch`?

**Comment by mkumatag** [comment]
This can be closed now...

/close
