### ISSUE TITLE
New API/Resource to import the PowerVS Image

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#474]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
This task is for creating a new Resource/controller for importing the image into PowerVS Service Instance

**Anything else you would like to add:**
Need a detailed design document for this work.

**Comment by mkumatag** [comment]
cc @Prajyot-Parab

**Comment by Prajyot-Parab** [comment]
```
// IBMPowerVSImageSpec defines the desired state of IBMPowerVSImage
type IBMPowerVSImageSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// ServiceInstanceID is the id of the power cloud instance where the image will get imported
	ServiceInstanceID string `json:"serviceInstanceID"`

	// Name for the image that will be loaded into the boot image catalog
	ImageName *string `json:"imageName"`

	// Indicates if the bucket has public or private access, public access require no authentication keys, private access requires hmac authentication keys (access,secret)
	// +kubebuilder:validation:Enum=public;private
	BucketAccess *string `json:"bucketAccess,omitempty"`

	// Cloud Object Storage bucket name; bucket-name[/optional/folder]
	BucketName *string `json:"bucketName"`

	// Cloud Object Storage image filename
	ImageFilename *string `json:"imageFilename"`

	// Cloud Object Storage region
	Region *string `json:"region"`

	// Type of storage, storage pool with the most available space will be selected
	// +optional
	StorageType string `json:"storageType,omitempty"`
}
```

**Comment by mkumatag** [comment]
> // IBMPowerVSImageSpec defines the desired state of IBMPowerVSImage
> type IBMPowerVSImageSpec struct {
> 	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
> 	// Important: Run "make" to regenerate code after modifying this file
> 
> 	// ServiceInstanceID is the id of the power cloud instance where the image will get imported
> 	ServiceInstanceID string `json:"serviceInstanceID"`
> 
> 	// Name for the image that will be loaded into the boot image catalog
> 	ImageName *string `json:"imageName"`

wondering if name can be used from the `IBMPowerVSImage.ObjectMeta.Name` directly
> 
> 	// Indicates if the bucket has public or private access, public access require no authentication keys, private access requires hmac authentication keys (access,secret)
> 	// +kubebuilder:validation:Enum=public;private
> 	BucketAccess *string `json:"bucketAccess,omitempty"`

Don't have any plan for the private images as of now, may be we can remove this field and assume bucket is public
> 
> 	// Cloud Object Storage bucket name; bucket-name[/optional/folder]
> 	BucketName *string `json:"bucketName"`
> 
> 	// Cloud Object Storage image filename
> 	ImageFilename *string `json:"imageFilename"`
> 
> 	// Cloud Object Storage region
> 	Region *string `json:"region"`
> 
> 	// Type of storage, storage pool with the most available space will be selected
> 	// +optional
> 	StorageType string `json:"storageType,omitempty"`

hope the default one is set in the webhook
> }
