### ISSUE TITLE
Enable POWER and s390x for IBM Cloud Provider

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#5]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
Some customer want to run cluster-api on IBM POWER or s390x, it is better to enable IBM Cloud cluster-api can run on those architecture platforms as well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
does IBM cloud current provide power arch vm? I know seems z is not in the list 

but yes, future switch to genisis might be another story

**Comment by gyliu513** [comment]
@jichenjc  Yes, IBM Cloud do support POWER, but not sure if it support Z or not, will check ;-)
