### ISSUE TITLE
Missing .git dir in postsubmit image push job

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cluster-api-provider-ibmcloud#560]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
In the [post-cluster-api-provider-ibmcloud-push-images](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-ibmcloud-push-images/1493471428199059456) job, there is an error in the [build logs](https://storage.googleapis.com/kubernetes-jenkins/logs/post-cluster-api-provider-ibmcloud-push-images/1493471428199059456/artifacts/build.log) about a missing .git dir. This same issue arose in CAPI and other provider repos when a git command is used but the .git dir isn't present. This results in the following errors below.

```
make docker-build-all
make[1]: Entering directory '/workspace'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make ARCH=amd64 docker-build
make[2]: Entering directory '/workspace'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
docker pull docker.io/docker/dockerfile:1.1-experimental
```

I've opened up a [PR](https://github.com/kubernetes/test-infra/pull/25251/files#) in test-infra that fixes the issue by including a flag in the prow jobs for all the providers listed there. I wanted to let the folks over here know about it and get an LGTM before merging any changes that could affect their prow jobs.

**Environment:**

- Cluster-api version: Any
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by mkumatag** [comment]
Mentioned PR https://github.com/kubernetes/test-infra/pull/25251 is already merged, hence closing this issue.

/close
