### ISSUE TITLE
publish v1beta1 compatible image? 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-ibmcloud#571]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

```
# clusterctl init --infrastructure ibmcloud
Fetching providers
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha4 for provider infrastructure-ibmcloud
```

looks like the latest ibmcloud is not ready for v1beta1 though we have v1beta1 API ?

looks like we need

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkumatag** [comment]
@jichenjc this is because we don't have any GA'ed release with v1beta1 yet, you can try with assigning version which are prereleased to work properly,

e.g:
```shell
clusterctl init --infrastructure ibmcloud:v0.2.0-alpha.5
```

**Comment by jichenjc** [comment]
ok, I will keep this open and use this to track the issue 

as https://cluster-api-ibmcloud.sigs.k8s.io/getting-started.html
indicated , <TAG> is input (v0.2.0-alpha.5) but no one knows which tag to use because no doc said that
thus they will encounter same issue here

**Comment by mkumatag** [comment]
agree, we can enhance the document to talk about that(pre and post release)

**Comment by mkumatag** [comment]
@Amulyam24 please check if there is a scope for improving the doc.
