### ISSUE TITLE
improve doc for IBMVPC_xxx variable definitions

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-ibmcloud#572]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

previously we have detailed doc on where the IBM_XXX variable comes from
now, with new VPC concept, I didn't find it related info .. I think we should doc this 

https://cluster-api-ibmcloud.sigs.k8s.io/topics/vpc/creating-a-cluster.html
```
IBMVPC_REGION=us-south \
IBMVPC_ZONE=us-south-1 \
IBMVPC_RESOURCEGROUP=4f15679623607b855b1a27a67f20e1c7 \
IBMVPC_NAME=ibm-vpc-0 \
IBMVPC_IMAGE_ID=r134-ea84bbec-7986-4ff5-8489-d9ec34611dd4 \
IBMVPC_PROFILE=bx2-4x16 \
IBMVPC_SSHKEY_ID=r134-2a82b725-e570-43d3-8b23-9539e8641944 \
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jichenjc** [comment]
only record here for resource group
https://cloud.ibm.com/docs/account?topic=account-rgs&interface=ui resource group 

@mkumatag 
do you have any existing eligible test machines 
`IBMVPC_IMAGE_ID=r134-ea84bbec-7986-4ff5-8489-d9ec34611dd4`
 that can be shared so I can do try? Thanks

**Comment by mkumatag** [comment]
> only record here for resource group https://cloud.ibm.com/docs/account?topic=account-rgs&interface=ui resource group
> 
> @mkumatag do you have any existing eligible test machines `IBMVPC_IMAGE_ID=r134-ea84bbec-7986-4ff5-8489-d9ec34611dd4` that can be shared so I can do try? Thanks

@wentao-zh has some images, he can help you will all the details
