### ISSUE TITLE
Explore clusterclass, machinepool, machinehealth apis

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#608]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/clusterclass_types.go
https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/api/v1beta1/machinepool_types.go
https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/machinehealthcheck_types.go

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Karthik-K-N** [comment]
1. Need to create a IBMPowerVSClusterTemplate: for reference https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/397

**Comment by mkumatag** [comment]
cluster class for vpc is already addressed via https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/974, hence closing this PR.
