### ISSUE TITLE
Code coverage for UT

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#636]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Explore different available options for the code coverage for the unit tests and adopt in the CICD

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Prajyot-Parab** [comment]
Code coverage prow job with data -[Testgrid]( https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-ibmcloud#capibm-periodic-coverage-main)
Prow Job config - [PR](https://github.com/kubernetes/test-infra/pull/26639)
Code updates - [PR](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/709)

**Comment by Prajyot-Parab** [comment]
@mkumatag This can be closed now.
