### ISSUE TITLE
Enhance the unit test coverage

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#662]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Here is the present unit test coverage as on 5th May 2022 which is really low, needs improvement

<img width="528" alt="image" src="https://user-images.githubusercontent.com/12646029/166886597-00a0cfc1-a5dd-4420-be45-2cf139bb69b5.png">

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Prajyot-Parab** [comment]
Findings -

cluster-api is using Gomega based approach for unit testing purposes. capi-ibmcloud should follow the same approach to be in sync with the capi project.

This might lead to major refactoring work in capi-ibmcloud to achieve the same. Also need to explore on helper methods available in capi for reusability purpose or write new ones mainly dealing with test env creation and deletion.

@Amulyam24 Please add if anything is missing

**Comment by Amulyam24** [comment]
After a discussion with @Prajyot-Parab, we have decided to follow the unit test framework of cluster-api by avoiding ginkgo.

- This would require modifying the current flow of bootstrapping the test environment by implementing helper methods, something similar to https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/test/helpers/envtest.go

- Once the framework is in place, we can proceed with adding the unit test cases thereby improving the coverage

**Comment by Prajyot-Parab** [comment]
Files targeted for UT coverage (divided into 2 groups PowerVS and VPC)

Functions to be mocked -
```
1. powervs_cluster.go / powervs_machine.go  / powervs_image.go -> NewPowerVSClusterScope -> authenticator.GetAuthenticator()
2. powervs_cluster.go / powervs_machine.go  / powervs_image.go -> NewPowerVSClusterScope -> servicesutils.GetAccount(auth)

Note - will update the list incase of further mocking required for any other functions.
```

```
PowerVS 

Cloud/Scope 
- powervs_cluster.go
 - powervs_machine.go 
 - powervs_image.go
 
   controllers 
   - ibmpowervscluster_controller.go 
   - ibmpowervsmachine_controller.go 
   - ibmpowervsimage_controller.go


 VPC

Cloud/Scope 
- cluster.go 
- machine.go

controllers 
- ibmvpccluster_controller.go 
- ibmvpcmachine_controller.go
```

Note - WIP: compiling list of scenarios to be covered in each of the targeted file, will update soon.

**Comment by Prajyot-Parab** [comment]
WIP list of the scenarios to be covered in IBMPowerVSCluster controller tests :
 
* [ ]  Reconcile IBMPowerVSCluster successfully:
  - Should set IBMPowerVSCluster status as ready if reconcile is successful
  - Should add finalizer to IBMPowerVSCluster

* [ ]  Reconcile IBMPowerVSCluster failures:
  - Should not set IBMPowerVSCluster status as ready if reconcile fails

* [ ]  Test Reconcile IBMPowerVSCluster func:
  - Should Reconcile IBMPowerVSCluster with requeue
  - Should fail Reconcile with GetOwnerCluster failure
  - Should Reconcile successfully if no IBMPowerVSCluster found
  - Should not create reconcile request for deleted clusters
  - Should not create reconcile request if infrastructure ref for IBMPowerVSCluster on owner cluster is not set
  - Should create reconcile request successfully

**Comment by Amulyam24** [comment]
WIP test scenarios for IBMPowerVS machine controller:
 

- [ ] Reconcile IBMPowerVSMachine

* Should reconcile successfully if IBMPowerVSMachine is not found
* Should reconcile if owner reference is not set
* Should reconcile successfully if IBMPowerVSCluster is not found
* Should reconcile successfully if IBMPowerVSImage is not found
* Should successfully reconcile IBMPowerVSMachine with requeue
* Should requeue if Cluster infrastructure status is not ready
* Should requeue if IBMPowerVSImage status is not ready
* Should requeue if boostrap data secret reference is not found
* Should fail to create IBMPowerVSMachine
* Should fail to get the PowerVS instance
* Should test IBMPowerVSMachine based on state
    * should requeue reconcile request if machine is in BUILD state
    * should reconcile if machine is in SHUTOFF state
    * should reconcile request if machine is in ACTIVE state
    * should reconcile if machine is in ERROR state
    * should requeue reconcile request if machine is in unknown state
* Should fail reconcile if error in fetching IBMPowerVSMachine
* Should fail to fetch cluster details from IBMPowerVSMachine metadata
* Should fail reconcile if Owner machine not found

- [ ]   Reconcile Delete IBMPowerVSMachine
* Should not delete IBMPowerVSMachine if instance ID not found
* Should fail to delete IBMPowerVSMachine
* Should delete IBMPowerVSMachine successfully

**Comment by Prajyot-Parab** [comment]
PRs

* [ ]  #726 
* [ ]  #734 
* [ ]  #741

**Comment by Prajyot-Parab** [comment]
Can be closed.
/close
