### ISSUE TITLE
centos support

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/cluster-api-provider-ibmcloud#73]
/kind feature

**Describe the solution you'd like**
we only support ubuntu machine on IBM cloud now.
It is preferred to support centos too

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
@hemanthavs

**Comment by jichenjc** [comment]
@hemanthavs you will take this into your work plan, right?

**Comment by hemanthavs** [comment]
yes @jichenjc, I started working on this Item

**Comment by jichenjc** [comment]
/assign @hemanthavs 

thanks :)
