### ISSUE TITLE
Add go-apidiff target

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes-sigs/cluster-api-provider-ibmcloud#789]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
- Check API compatibility between different revisions of a Go project.

Ref - https://github.com/kubernetes-sigs/controller-runtime/issues/681

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkumatag** [comment]
@Prajyot-Parab can you be more descriptive how this tool is going to help us and the sample runs with output

**Comment by Prajyot-Parab** [comment]
Added `newRegion` to `api/v1beta1/ibmpowervsimage_types.go`
Renamed `Region` to `newRegion` in `api/v1alpha3/ibmvpccluster_types.go`

Sample - 

```
prajyotparab@Prajyots-MBP cluster-api-provider-ibmcloud % make apidiff                         
make -C hack/tools bin/go-apidiff
make[1]: `bin/go-apidiff' is up to date.
api/v1alpha3/ibmvpccluster_types.go
api/v1beta1/ibmpowervsimage_types.go

sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1beta1
  Compatible changes:
  - IBMPowerVSImageSpec.NewRegion: added

sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1alpha3
  Incompatible changes:
  - IBMVPCClusterSpec.Region: removed
  Compatible changes:
  - IBMVPCClusterSpec.NewRegion: added
make: *** [apidiff] Error 1
```

**Comment by mkumatag** [comment]
@Prajyot-Parab thanks for adding this additional information, but how to consume this information, are we adding this as an additional check into the `make verify` target or some other way?

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab thanks for adding this additional information, but how to consume this information, are we adding this as an additional check into the `make verify` target or some other way?

@mkumatag I plan to consume it via api-diff pre-submit-job (to be added) same as other providers.

**Comment by Prajyot-Parab** [comment]
> > @Prajyot-Parab thanks for adding this additional information, but how to consume this information, are we adding this as an additional check into the `make verify` target or some other way?
> 
> @mkumatag I plan to consume it via api-diff pre-submit-job (to be added) same as other providers.

will add the additional required files as part o this PR itself.

**Comment by mkumatag** [comment]
> > > @Prajyot-Parab thanks for adding this additional information, but how to consume this information, are we adding this as an additional check into the `make verify` target or some other way?
> > 
> > 
> > @mkumatag I plan to consume it via api-diff pre-submit-job (to be added) same as other providers.
> 
> will add the additional required files as part o this PR itself.

Lets add that in the verify target in the PR then.

**Comment by mkumatag** [comment]
> > @Prajyot-Parab thanks for adding this additional information, but how to consume this information, are we adding this as an additional check into the `make verify` target or some other way?
> 
> @mkumatag I plan to consume it via api-diff pre-submit-job (to be added) same as other providers.

ah! is this going to be part of `verify` or planning to add a different job all together for this alone?

**Comment by Prajyot-Parab** [comment]
> > > @Prajyot-Parab thanks for adding this additional information, but how to consume this information, are we adding this as an additional check into the `make verify` target or some other way?
> > 
> > 
> > @mkumatag I plan to consume it via api-diff pre-submit-job (to be added) same as other providers.
> 
> ah! is this going to be part of `verify` or planning to add a different job all together for this alone?

A different Job for this one.
