### ISSUE TITLE
Follow the capi-api logging standards

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#844]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
https://cluster-api.sigs.k8s.io/developer/logging.html

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkumatag** [comment]
@Karthik-K-N can you update this issue and close if nothing else needed here

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N can you update this issue and close if nothing else needed here

Sure I will do that

**Comment by Karthik-K-N** [comment]
CAPI logging standards can seen here: https://cluster-api.sigs.k8s.io/developer/logging.html#log-levels

A PR https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/895 is already been merged to follow the CAPI logging standards.

will close this issue and incase of any improvement needed in logging it will be taken care during later stages if found necessary.

/close
