### ISSUE TITLE
do we have plan to support different k8s vendor

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-ibmcloud#87]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

do we have plan to support the different k8s vendor like ICP or some others and the user cases was:

1) If I already have a ICP cluster, I want to use cluster api to deploy the ICP and use the MCM to manage the provided ICP cluster.
2) If I already have a ICP cluster, I can use cluster api to deploy other vendor k8s but I want to use ICP MCM to manage those cluster.
3) If I did not have a ICP cluster, but I want to use ICP to have some IBM application running, so I may use cluster api to deploy an ICP cluster and deploy the IBM application(from ICP catalog) running on ICP k8s.

cc @gyliu513 @xunpan 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by xunpan** [comment]
This project has no plan for doing this.

It is traced in `cluster-api`  https://github.com/kubernetes-sigs/cluster-api/issues/853

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/997/ is on the way
I think we need defer this to align with v1alpha2
