### ISSUE TITLE
Presubmit job for building the ccm image

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#870]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**

Like we have presubmit for building image for the capibm, we should also have similar for the ccm image
https://github.com/kubernetes/test-infra/blob/dd23d28cfe4d64e30d1749169e8e87dfe888d317/config/jobs/kubernetes-sigs/cluster-api-provider-ibmcloud/cluster-api-provider-ibmcom-presubmits.yaml#L3:L28

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag should we have the presubmit job pointing to https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/hack/ccm/Dockerfile I mean looking for a change here?

**Comment by mkumatag** [comment]
> @mkumatag should we have the presubmit job pointing to https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/hack/ccm/Dockerfile I mean looking for a change here?

yes, I'm looking for a presubmit job for this docker build which should trigger only if `hack/ccm` folder changed

**Comment by Rajalakshmi-Girish** [comment]
Added by https://github.com/kubernetes/test-infra/pull/27682
@mkumatag This issue may be closed.

**Comment by mkumatag** [comment]
> Added by [kubernetes/test-infra#27682](https://github.com/kubernetes/test-infra/pull/27682)
> @mkumatag This issue may be closed.

Its always good to link the issues in the PR so that it will get closed automatically post-merge, [more information](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by Rajalakshmi-Girish** [comment]
> Its always good to link the issues in the PR so that it will get closed automatically post-merge
Yes, but I thought the `issue` and `PR` must be from the same repo to link them.

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag Thanks for the info!
