### ISSUE TITLE
Repo Migration Request

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#89]
It is being traced at https://github.com/kubernetes-sigs/cluster-api/issues/921

FYI @jichenjc @xunpan

**Comment by jichenjc** [comment]
thank you, looks like we should not ask in cluster-api instead some place else?

**Comment by gyliu513** [comment]
no worry, I have talked this in both slack channel and email list, I'm going to do a demo for cluster api in next Wednesday.

**Comment by jichenjc** [comment]
ok, good to know :)

**Comment by gyliu513** [comment]
Migrated to `kubernetes-sigs` now !!
