### ISSUE TITLE
Add scale from and to 0 support for autoscaler for VPC cluster

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#959]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Respective Power VS PR to add support https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/860

**Comment by mkumatag** [comment]
@Karthik-K-N lets find out who wants to take this up.

**Comment by mkumatag** [comment]
@KeerthanaAP any further updates on this issue?

**Comment by mkumatag** [comment]
I still see code review is pending and is not blocking the release, hence moving to next release
