### ISSUE TITLE
Add ClusterClass support for VPC

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#974]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
ClusterClass support for Power VS was added as a part of https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/967, Similar approach can be taken for VPC

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Sajiyah-Salat** [comment]
Hello, can you please explain this pr?

**Comment by Shilpa-Gokul** [comment]
I would like to work on this issue

**Comment by swastik959** [comment]
@Karthik-K-N hi I have created a pull request can you please review and let me know if this is what you want

**Comment by Amulyam24** [comment]
Added by #1500 
/close
